# 🔎 Levantamento e Exploração das Fontes de Dados

Tech Challenge — Avaliação da Alfabetização

Este notebook faz parte da etapa de levantamento e exploração das fontes de dados utilizadas no desenvolvimento do projeto.

O objetivo desta etapa é conhecer a estrutura das bases disponíveis antes da implementação dos tratamentos e cruzamentos nas camadas da arquitetura de dados.

## 🎯 Objetivos deste levantamento

Nesta etapa buscamos:

- identificar as fontes de dados disponíveis para o projeto;
- identificar as tabelas, arquivos e estruturas existentes em cada fonte;
- levantar as colunas disponíveis em cada tabela;
- identificar os tipos de dados das variáveis;
- identificar possíveis chaves de relacionamento;
- verificar a cobertura temporal e geográfica das informações;
- identificar quais informações podem contribuir para responder às perguntas de negócio do projeto;
- avaliar a necessidade de fontes complementares.

## 🎯 Pergunta central do projeto

O levantamento das fontes será orientado pela necessidade de compreender o alcance das metas de alfabetização e investigar como os resultados podem se relacionar com características educacionais e socioeconômicas dos municípios e estados.

As perguntas de análise serão refinadas pela equipe à medida que as variáveis disponíveis nas diferentes fontes forem identificadas.

## 🏗️ Relação com a arquitetura do projeto

O levantamento realizado neste notebook antecede a implementação das camadas de dados na AWS.

O fluxo considerado para o projeto é:

**Fontes de dados → Bronze → Prata → Gold → Visualização**

Neste momento, o notebook **não tem como objetivo realizar a modelagem definitiva das camadas**.

A finalidade é entender o conteúdo e a estrutura das fontes para apoiar as decisões que serão tomadas posteriormente pela equipe.

### 🥉 Camada Bronze

A camada Bronze será responsável pelo armazenamento dos dados provenientes das fontes selecionadas, mantendo-os o mais próximo possível de sua origem.

O levantamento realizado neste notebook ajudará a equipe a definir quais arquivos, tabelas e informações deverão ser considerados nessa etapa.

### 🥈 Camada Prata

Na camada Prata serão realizados os tratamentos necessários sobre os dados, como:

- seleção das variáveis necessárias;
- padronização;
- tratamento de valores ausentes;
- ajustes de tipos;
- filtros;
- preparação dos dados para os relacionamentos.

### 🥇 Camada Gold

A camada Gold será construída posteriormente com os dados tratados e organizados para responder às perguntas definidas para o projeto.

Nesta etapa poderão ser criados indicadores, relacionamentos e estruturas específicas para análise e visualização.

## 📚 Fontes de dados analisadas

Para o desenvolvimento do projeto, foram exploradas três fontes de dados:

1. **Avaliação da Alfabetização — Base dos Dados**
   - Fonte principal do projeto.

2. **Censo Escolar 2023 — INEP**
   - Fonte complementar para informações sobre o contexto e a estrutura educacional.

3. **INSE 2023 — INEP**
   - Fonte complementar para informações relacionadas ao nível socioeconômico.

A seleção das fontes considerou a disponibilidade dos dados, o recorte temporal de 2023, a estrutura das informações e seu potencial de contribuição para as análises propostas.

## 📌 Metodologia do levantamento

Para cada fonte ou tabela analisada, são identificados:

1. nome da fonte;
2. nome da tabela ou arquivo;
3. quantidade de colunas;
4. nome das colunas;
5. tipo de dado;
6. possíveis chaves de relacionamento;
7. finalidade das informações dentro do projeto.

As consultas realizadas neste notebook têm caráter exploratório e documental. O objetivo é registrar o processo de descoberta e avaliação das fontes antes da implementação da arquitetura final.

## 1. Base Principal — Avaliação da Alfabetização

In [ ]:
!pip install -q basedosdados

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 17.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.9/214.9 kB 9.0 MB/s eta 0:00:00

In [ ]:
import basedosdados as bd
from google.cloud import bigquery

### 1.1 Estrutura das tabelas

In [ ]:
PROJECT_ID = "primeval-melody-504216-n5"

client = bigquery.Client(project=PROJECT_ID)

print("Projeto configurado:", client.project)

Projeto configurado: primeval-melody-504216-n5

In [ ]:
from google.colab import auth

auth.authenticate_user()

### 1.2 Tabela `alunos`

In [ ]:
# TABELA ALUNOS
table_ref = "basedosdados.br_inep_avaliacao_alfabetizacao.alunos"

table = client.get_table(table_ref)

print("Tabela:", table.full_table_id)
print("Número de colunas:", len(table.schema))

Tabela: basedosdados:br_inep_avaliacao_alfabetizacao.alunos
Número de colunas: 12

In [ ]:
for campo in table.schema:
    print(f"{campo.name} → {campo.field_type}")

ano → INTEGER
id_municipio → STRING
id_escola → STRING
id_aluno → STRING
caderno → STRING
serie → STRING
rede → STRING
presenca → STRING
preenchimento_caderno → STRING
alfabetizado → STRING
proficiencia → FLOAT
peso_aluno → FLOAT

###1.3 Tabela Municipio

In [ ]:
# TABELA MUNICÍPIO

table_ref = "basedosdados.br_inep_avaliacao_alfabetizacao.municipio"

In [ ]:
table = client.get_table(table_ref)

print("Tabela:", table.full_table_id)
print("Número de colunas:", len(table.schema))

Tabela: basedosdados:br_inep_avaliacao_alfabetizacao.municipio
Número de colunas: 15

In [ ]:
for campo in table.schema:
    print(f"{campo.name} → {campo.field_type}")

ano → INTEGER
id_municipio → STRING
serie → STRING
rede → STRING
taxa_alfabetizacao → FLOAT
media_portugues → FLOAT
proporcao_aluno_nivel_0 → FLOAT
proporcao_aluno_nivel_1 → FLOAT
proporcao_aluno_nivel_2 → FLOAT
proporcao_aluno_nivel_3 → FLOAT
proporcao_aluno_nivel_4 → FLOAT
proporcao_aluno_nivel_5 → FLOAT
proporcao_aluno_nivel_6 → FLOAT
proporcao_aluno_nivel_7 → FLOAT
proporcao_aluno_nivel_8 → FLOAT

Observação

A tabela `municipio` apresenta indicadores agregados por município,
incluindo taxa de alfabetização, média de Português e distribuição
dos alunos segundo níveis de proficiência.

O campo `id_municipio` será posteriormente avaliado como possível
chave de relacionamento com as demais bases utilizadas no projeto.

### 1.4 Tabela `uf`

In [ ]:
# TABELA UF

table_ref = "basedosdados.br_inep_avaliacao_alfabetizacao.uf"

table = client.get_table(table_ref)

print("Tabela:", table.full_table_id)
print("Número de colunas:", len(table.schema))

for campo in table.schema:
    print(f"{campo.name} → {campo.field_type}")

Tabela: basedosdados:br_inep_avaliacao_alfabetizacao.uf
Número de colunas: 15
ano → INTEGER
sigla_uf → STRING
serie → STRING
rede → STRING
taxa_alfabetizacao → FLOAT
media_portugues → FLOAT
proporcao_aluno_nivel_0 → FLOAT
proporcao_aluno_nivel_1 → FLOAT
proporcao_aluno_nivel_2 → FLOAT
proporcao_aluno_nivel_3 → FLOAT
proporcao_aluno_nivel_4 → FLOAT
proporcao_aluno_nivel_5 → FLOAT
proporcao_aluno_nivel_6 → FLOAT
proporcao_aluno_nivel_7 → FLOAT
proporcao_aluno_nivel_8 → FLOAT

### 1.5 Tabela `meta_alfabetizacao_brasil`

In [ ]:
# TABELA ALFABETIZAÇÃO BRASIL

table_ref = "basedosdados.br_inep_avaliacao_alfabetizacao.meta_alfabetizacao_brasil"

table = client.get_table(table_ref)

print("Tabela:", table.full_table_id)
print("Número de colunas:", len(table.schema))

Tabela: basedosdados:br_inep_avaliacao_alfabetizacao.meta_alfabetizacao_brasil
Número de colunas: 11

In [ ]:
for campo in table.schema:
    print(f"{campo.name} → {campo.field_type}")

ano → INTEGER
rede → STRING
taxa_alfabetizacao → FLOAT
meta_alfabetizacao_2024 → FLOAT
meta_alfabetizacao_2025 → FLOAT
meta_alfabetizacao_2026 → FLOAT
meta_alfabetizacao_2027 → FLOAT
meta_alfabetizacao_2028 → FLOAT
meta_alfabetizacao_2029 → FLOAT
meta_alfabetizacao_2030 → FLOAT
percentual_participacao → FLOAT

Observação

A tabela `meta_alfabetizacao_brasil` possui 11 colunas e apresenta
informações agregadas em nível nacional.

Além do ano, rede de ensino e taxa de alfabetização, a tabela
disponibiliza metas de alfabetização projetadas para o período de
2024 a 2030 e o percentual de participação.

A presença da taxa de alfabetização e das metas em uma mesma tabela
permite, posteriormente, avaliar a distância entre o resultado
observado e as metas estabelecidas.

### 1.6 Tabela `meta_alfabetizacao_municipio`

In [ ]:
# TABELA ALFABETIZACAO MUNICIPIO

table_ref = "basedosdados.br_inep_avaliacao_alfabetizacao.meta_alfabetizacao_municipio"

table = client.get_table(table_ref)

print("Tabela:", table.full_table_id)
print("Número de colunas:", len(table.schema))

Tabela: basedosdados:br_inep_avaliacao_alfabetizacao.meta_alfabetizacao_municipio
Número de colunas: 13

In [ ]:
for campo in table.schema:
    print(f"{campo.name} → {campo.field_type}")

ano → INTEGER
id_municipio → STRING
rede → STRING
taxa_alfabetizacao → FLOAT
meta_alfabetizacao_2024 → FLOAT
meta_alfabetizacao_2025 → FLOAT
meta_alfabetizacao_2026 → FLOAT
meta_alfabetizacao_2027 → FLOAT
meta_alfabetizacao_2028 → FLOAT
meta_alfabetizacao_2029 → FLOAT
meta_alfabetizacao_2030 → FLOAT
nivel_alfabetizacao → INTEGER
percentual_participacao → FLOAT

Observação

A tabela `meta_alfabetizacao_municipio` possui 13 colunas e apresenta
informações agregadas em nível municipal.

Além da taxa e do nível de alfabetização, a tabela disponibiliza
metas projetadas para o período de 2024 a 2030, percentual de
participação e o identificador `id_municipio`.

O campo `id_municipio` será posteriormente avaliado como chave de
relacionamento com outras tabelas da base de Avaliação da
Alfabetização e com bases educacionais adicionais que possuam o
mesmo identificador ou mecanismo de correspondência municipal.

### 1.7 Tabela `meta_alfabetizacao_uf`

In [ ]:
# TABELA ALFABETIZACAO UF

table_ref = "basedosdados.br_inep_avaliacao_alfabetizacao.meta_alfabetizacao_uf"

table = client.get_table(table_ref)

print("Tabela:", table.full_table_id)
print("Número de colunas:", len(table.schema))

Tabela: basedosdados:br_inep_avaliacao_alfabetizacao.meta_alfabetizacao_uf
Número de colunas: 12

In [ ]:
for campo in table.schema:
    print(f"{campo.name} → {campo.field_type}")

ano → INTEGER
sigla_uf → STRING
rede → STRING
taxa_alfabetizacao → FLOAT
meta_alfabetizacao_2024 → FLOAT
meta_alfabetizacao_2025 → FLOAT
meta_alfabetizacao_2026 → FLOAT
meta_alfabetizacao_2027 → FLOAT
meta_alfabetizacao_2028 → FLOAT
meta_alfabetizacao_2029 → FLOAT
meta_alfabetizacao_2030 → FLOAT
percentual_participacao → FLOAT

### 1.8 Tabela `dicionario`

In [ ]:
table_ref = "basedosdados.br_inep_avaliacao_alfabetizacao.dicionario"

table = client.get_table(table_ref)

print("Tabela:", table.full_table_id)
print("Número de colunas:", len(table.schema))

Tabela: basedosdados:br_inep_avaliacao_alfabetizacao.dicionario
Número de colunas: 5

In [ ]:
for campo in table.schema:
    print(f"{campo.name} → {campo.field_type}")

id_tabela → STRING
nome_coluna → STRING
chave → STRING
cobertura_temporal → STRING
valor → STRING

Observação

A tabela `dicionario` possui 5 colunas e funciona como uma tabela
de metadados da base.

Os campos `id_tabela` e `nome_coluna` permitem identificar a qual
tabela e variável determinada informação está relacionada. Os
campos `chave`, `cobertura_temporal` e `valor` complementam as
informações necessárias para interpretação das variáveis.

Por se tratar de uma tabela de apoio, seus dados não representam
diretamente os resultados de alfabetização, mas serão utilizados
como referência para interpretação e documentação das demais
tabelas.

### 1.9 🎯 Objetivos da análise — Metas de Alfabetização

A Avaliação da Alfabetização é a base principal deste projeto e tem
como objetivo analisar os resultados de alfabetização e sua relação
com as metas estabelecidas.

Nesta etapa, serão analisadas as tabelas relacionadas às metas em
diferentes níveis geográficos, permitindo posteriormente realizar
cruzamentos com outras bases educacionais.

**Estrutura das tabelas de metas**

| Nível | Tabela | Objetivo da análise |
|---|---|---|
| 🇧🇷 Brasil | `meta_alfabetizacao_brasil` | Identificar a meta nacional de alfabetização |
| 🏙️ Município | `meta_alfabetizacao_municipio` | Analisar as metas estabelecidas para cada município |
| 🗺️ UF | `meta_alfabetizacao_uf` | Comparar as metas e resultados entre as Unidades da Federação |
| 📍 Referência | `uf` | Identificar e relacionar as Unidades da Federação |

**🔎 Perguntas que pretendemos responder**

A análise será orientada pelas seguintes perguntas:

### 1. Alcance das metas
- Qual é a meta de alfabetização estabelecida para o período analisado?
- Quais municípios atingiram ou superaram a meta?
- Quais municípios ficaram abaixo da meta?
- Qual é a proporção de municípios que atingiram a meta?

### 2. Comparação entre estados
- Quais Unidades da Federação apresentam os melhores resultados?
- Quais estados apresentam maior distância em relação à meta?
- Existem diferenças relevantes no desempenho entre as UFs?
- Quais estados apresentam maior concentração de municípios abaixo da meta?

### 3. Desempenho e alfabetização
- Existe relação entre a taxa de alfabetização e o alcance da meta?
- Como a distribuição dos níveis de proficiência se relaciona com o
  cumprimento das metas?
- Quais municípios apresentam bons resultados mesmo estando abaixo
  da meta?

### 4. Cruzamento com outras bases
Posteriormente, os resultados das metas poderão ser relacionados a outras bases selecionadas, como:

- **Censo Escolar:** infraestrutura, matrículas, docentes e características das escolas;
- **INSE:** nível socioeconômico dos estudantes e das escolas.

Esses cruzamentos permitirão investigar possíveis relações entre o
contexto educacional e socioeconômico e o alcance das metas de
alfabetização.

**🎯 Resultado esperado**

A partir dos cruzamentos, pretende-se construir indicadores que
permitam visualizar:

**Meta → Resultado → Diferença → Contexto educacional → Contexto socioeconômico**

Esses indicadores serão utilizados posteriormente na definição da
**camada GOLD** e na construção da visualização.

## Inventário da Base Principal

## Base: `br_inep_avaliacao_alfabetizacao`

A base de Avaliação da Alfabetização é a base principal do projeto.
Abaixo está o inventário das tabelas identificadas, seus campos e
respectivos tipos de dados.

---

## 1. Tabela `alunos`

**Quantidade de colunas:** 12

| Campo | Tipo |
|---|---|
| `ano` | INTEGER |
| `id_municipio` | STRING |
| `id_escola` | STRING |
| `id_aluno` | STRING |
| `caderno` | STRING |
| `serie` | STRING |
| `rede` | STRING |
| `presenca` | STRING |
| `preenchimento_caderno` | STRING |
| `alfabetizado` | STRING |
| `proficiencia` | FLOAT |
| `peso_aluno` | FLOAT |

**Finalidade:** dados relacionados aos alunos participantes da
avaliação, incluindo informações de identificação, participação,
alfabetização e proficiência.

---

## 2. Tabela `municipio`

**Quantidade de colunas:** 15

| Campo | Tipo |
|---|---|
| `ano` | INTEGER |
| `id_municipio` | STRING |
| `serie` | STRING |
| `rede` | STRING |
| `taxa_alfabetizacao` | FLOAT |
| `media_portugues` | FLOAT |
| `proporcao_aluno_nivel_0` | FLOAT |
| `proporcao_aluno_nivel_1` | FLOAT |
| `proporcao_aluno_nivel_2` | FLOAT |
| `proporcao_aluno_nivel_3` | FLOAT |
| `proporcao_aluno_nivel_4` | FLOAT |
| `proporcao_aluno_nivel_5` | FLOAT |
| `proporcao_aluno_nivel_6` | FLOAT |
| `proporcao_aluno_nivel_7` | FLOAT |
| `proporcao_aluno_nivel_8` | FLOAT |

**Finalidade:** indicadores agregados de alfabetização e desempenho
em nível municipal.

---

## 3. Tabela `uf`

**Quantidade de colunas:** 15

| Campo | Tipo |
|---|---|
| `ano` | INTEGER |
| `sigla_uf` | STRING |
| `serie` | STRING |
| `rede` | STRING |
| `taxa_alfabetizacao` | FLOAT |
| `media_portugues` | FLOAT |
| `proporcao_aluno_nivel_0` | FLOAT |
| `proporcao_aluno_nivel_1` | FLOAT |
| `proporcao_aluno_nivel_2` | FLOAT |
| `proporcao_aluno_nivel_3` | FLOAT |
| `proporcao_aluno_nivel_4` | FLOAT |
| `proporcao_aluno_nivel_5` | FLOAT |
| `proporcao_aluno_nivel_6` | FLOAT |
| `proporcao_aluno_nivel_7` | FLOAT |
| `proporcao_aluno_nivel_8` | FLOAT |

**Finalidade:** indicadores agregados de alfabetização e desempenho
em nível estadual.

---

## 4. Tabela `meta_alfabetizacao_brasil`

**Quantidade de colunas:** 11

| Campo | Tipo |
|---|---|
| `ano` | INTEGER |
| `rede` | STRING |
| `taxa_alfabetizacao` | FLOAT |
| `meta_alfabetizacao_2024` | FLOAT |
| `meta_alfabetizacao_2025` | FLOAT |
| `meta_alfabetizacao_2026` | FLOAT |
| `meta_alfabetizacao_2027` | FLOAT |
| `meta_alfabetizacao_2028` | FLOAT |
| `meta_alfabetizacao_2029` | FLOAT |
| `meta_alfabetizacao_2030` | FLOAT |
| `percentual_participacao` | FLOAT |

**Finalidade:** metas e indicadores de alfabetização em nível nacional.

---

## 5. Tabela `meta_alfabetizacao_municipio`

**Quantidade de colunas:** 13

| Campo | Tipo |
|---|---|
| `ano` | INTEGER |
| `id_municipio` | STRING |
| `rede` | STRING |
| `taxa_alfabetizacao` | FLOAT |
| `meta_alfabetizacao_2024` | FLOAT |
| `meta_alfabetizacao_2025` | FLOAT |
| `meta_alfabetizacao_2026` | FLOAT |
| `meta_alfabetizacao_2027` | FLOAT |
| `meta_alfabetizacao_2028` | FLOAT |
| `meta_alfabetizacao_2029` | FLOAT |
| `meta_alfabetizacao_2030` | FLOAT |
| `nivel_alfabetizacao` | INTEGER |
| `percentual_participacao` | FLOAT |

**Finalidade:** metas e indicadores de alfabetização em nível municipal.

---

## 6. Tabela `meta_alfabetizacao_uf`

**Quantidade de colunas:** 12

| Campo | Tipo |
|---|---|
| `ano` | INTEGER |
| `sigla_uf` | STRING |
| `rede` | STRING |
| `taxa_alfabetizacao` | FLOAT |
| `meta_alfabetizacao_2024` | FLOAT |
| `meta_alfabetizacao_2025` | FLOAT |
| `meta_alfabetizacao_2026` | FLOAT |
| `meta_alfabetizacao_2027` | FLOAT |
| `meta_alfabetizacao_2028` | FLOAT |
| `meta_alfabetizacao_2029` | FLOAT |
| `meta_alfabetizacao_2030` | FLOAT |
| `percentual_participacao` | FLOAT |

**Finalidade:** metas e indicadores de alfabetização em nível estadual.

---

## 7. Tabela `dicionario`

**Quantidade de colunas:** 5

| Campo | Tipo |
|---|---|
| `id_tabela` | STRING |
| `nome_coluna` | STRING |
| `chave` | STRING |
| `cobertura_temporal` | STRING |
| `valor` | STRING |

**Finalidade:** tabela de metadados utilizada como apoio à
interpretação das variáveis das demais tabelas.

---

# 🔑 Principais campos para relacionamento

| Campo | Tabelas | Possível utilização |
|---|---|---|
| `id_municipio` | `alunos`, `municipio`, `meta_alfabetizacao_municipio` | Relacionamento em nível municipal |
| `sigla_uf` | `uf`, `meta_alfabetizacao_uf` | Relacionamento em nível estadual |
| `ano` | diversas tabelas | Relacionamento temporal |
| `rede` | diversas tabelas | Segmentação por rede de ensino |
| `serie` | `alunos`, `municipio`, `uf` | Segmentação por série |

## Consulta de municípios - API IBGE

Para complementar as bases utilizadas no projeto, será utilizada a
API de Localidades do IBGE para obter a relação de municípios
brasileiros.

A API disponibiliza o código IBGE do município e seu respectivo nome,
permitindo relacionar essas informações ao campo `id_municipio`
presente nas tabelas da Base dos Dados.

Endpoint utilizado:

https://servicodados.ibge.gov.br/api/v1/localidades/municipios

A consulta não requer autenticação.

In [ ]:
import requests
import pandas as pd

url = "https://servicodados.ibge.gov.br/api/v1/localidades/municipios"

resposta = requests.get(url)
resposta.raise_for_status()

dados = resposta.json()

print(f"Quantidade de registros retornados: {len(dados)}")

Quantidade de registros retornados: 5571

In [ ]:
municipios = pd.DataFrame([
    {
        "id_municipio": str(municipio["id"]),
        "nome_municipio": municipio["nome"]
    }
    for municipio in dados
])

municipios.head()

  id_municipio         nome_municipio
0      1100015  Alta Floresta D'Oeste
1      1100023              Ariquemes
2      1100031                 Cabixi
3      1100049                 Cacoal
4      1100056             Cerejeiras

In [ ]:
print("Quantidade de municípios:", len(municipios))
print("Códigos de municípios únicos:", municipios["id_municipio"].nunique())

Quantidade de municípios: 5571
Códigos de municípios únicos: 5571

In [ ]:
print("IDs nulos:", municipios["id_municipio"].isna().sum())
print("Nomes nulos:", municipios["nome_municipio"].isna().sum())

IDs nulos: 0
Nomes nulos: 0

Observação

A API de Localidades do IBGE foi consultada para verificar a
disponibilidade de uma fonte oficial contendo o código e o nome
dos municípios brasileiros.

A consulta retornou 5.571 municípios, com 5.571 códigos únicos e
sem valores nulos para código ou nome do município.

Nesta etapa, os dados são utilizados exclusivamente para
levantamento e avaliação da fonte. A definição das colunas que
serão carregadas para a camada Bronze e os tratamentos que serão
realizados na camada Prata serão definidos posteriormente,
conforme a modelagem do projeto.

# 🏫 Fonte Complementar 1 — Censo Escolar 2023

O Censo Escolar será analisado como fonte complementar à Avaliação
da Alfabetização, com o objetivo de identificar informações
relacionadas à estrutura e ao contexto da educação básica.

Nesta etapa será realizado um levantamento completo da estrutura dos
dados disponibilizados pelo INEP, sem aplicação de filtros ou
seleção prévia de variáveis.

Serão identificados:

- arquivos e estruturas disponíveis;
- tabelas/estruturas de dados;
- quantidade de colunas;
- nomes das colunas;
- tipos de dados;
- possíveis chaves de relacionamento;
- informações relevantes para análises posteriores.

A definição das variáveis que serão utilizadas nas camadas Bronze,
Prata e Gold será realizada posteriormente pela equipe.

## 🔎 2.1 Estrutura: microdados_unidade_coleta

A estrutura `microdados_unidade_coleta` representa os dados dos
microdados da unidade de coleta do Censo Escolar da Educação Básica
2023.

Nesta etapa será realizado o levantamento das variáveis disponíveis,
sem aplicação de filtros.

## 📖 2.2 Dicionário de Dados — Censo Escolar 2023

O dicionário de dados disponibilizado pelo INEP será utilizado como
referência para identificar as estruturas e variáveis existentes
nos microdados do Censo Escolar.

In [ ]:
from google.colab import files

arquivo = files.upload()

Saving dicionário_dados_educação_básica.xlsx to dicionário_dados_educação_básica.xlsx

In [ ]:
import os

print(os.listdir())

['.config', 'dicionário_dados_educação_básica.xlsx', 'sample_data']

In [ ]:
import pandas as pd

arquivo_dicionario = "dicionário_dados_educação_básica.xlsx"

excel = pd.ExcelFile(arquivo_dicionario)

print("Abas disponíveis:")
for aba in excel.sheet_names:
    print(f"- {aba}")

Abas disponíveis:
- microdados_unidade_coleta
- suplemento_cursos_tecnicos

In [ ]:
df_dicionario = pd.read_excel(
    arquivo_dicionario,
    sheet_name="microdados_unidade_coleta"
)

print("Linhas:", df_dicionario.shape[0])
print("Colunas:", df_dicionario.shape[1])

print("\nNome das colunas:")
for coluna in df_dicionario.columns:
    print(f"- {coluna}")

Linhas: 471
Colunas: 24

Nome das colunas:
- Unnamed: 0
- Alteração de nomenclatura ou metodologia de cálculo
- Unnamed: 2
- Unnamed: 3
- Unnamed: 4
- Unnamed: 5
- Unnamed: 6
- Unnamed: 7
- Unnamed: 8
- Unnamed: 9
- Unnamed: 10
- Unnamed: 11
- Unnamed: 12
- Unnamed: 13
- Unnamed: 14
- Unnamed: 15
- Unnamed: 16
- Unnamed: 17
- Unnamed: 18
- Unnamed: 19
- Unnamed: 20
- Unnamed: 21
- Unnamed: 22
- Unnamed: 23

Como nao localizamos o cabecarios na primeira linha vamos verificar as 15 primeiras linhas para identificar os dados

In [ ]:
df_bruto = pd.read_excel(
    arquivo_dicionario,
    sheet_name="microdados_unidade_coleta",
    header=None
)

df_bruto.head(15)

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,NaN,Alteração de nomenclatura ou metodologia de cá...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Variável nova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Descontinuidade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Dicionário de Variáveis - Tabela de Escolas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,N,Nome da Variável,Descrição da Variável,Tipo,Tam.(1),Categoria,"Coleta por ano (""s""=sim;""n""=não )",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Notas Importantes
7,NaN,NaN,NaN,NaN,NaN,NaN,07,08,09,10,...,15,16,17,18,19,20,21,22,23,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1,NU_ANO_CENSO,Ano do Censo,Num,4,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN
10,2,NO_REGIAO,Nome da Região Geográfica,Char,20,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN
11,3,CO_REGIAO,Código da Região Geográfica,Num,1,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN
12,4,NO_UF,Nome da Unidade da Federação,Char,50,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN
13,5,SG_UF,Sigla da Unidade da Federação,Char,2,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN
14,6,CO_UF,Código da Unidade da Federação,Num,2,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN

In [ ]:
df_censo = pd.read_excel(
    arquivo_dicionario,
    sheet_name="microdados_unidade_coleta",
    header=6
)

print("Linhas:", df_censo.shape[0])
print("Colunas:", df_censo.shape[1])

print("\nColunas do dicionário:")
for coluna in df_censo.columns:
    print(f"- {coluna}")

Linhas: 465
Colunas: 24

Colunas do dicionário:
- N
- Nome da Variável
- Descrição da Variável
- Tipo
- Tam.(1)
- Categoria
- Coleta por ano ("s"=sim;"n"=não )
- Unnamed: 7
- Unnamed: 8
- Unnamed: 9
- Unnamed: 10
- Unnamed: 11
- Unnamed: 12
- Unnamed: 13
- Unnamed: 14
- Unnamed: 15
- Unnamed: 16
- Unnamed: 17
- Unnamed: 18
- Unnamed: 19
- Unnamed: 20
- Unnamed: 21
- Unnamed: 22
- Notas Importantes

In [ ]:
# Identifica os anos presentes nas colunas de coleta
anos = df_censo.iloc[0, 7:24].tolist()

print("Anos de coleta:")
print(anos)

Anos de coleta:
['08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', nan]

In [ ]:
# Identifica somente os anos de coleta
anos = df_censo.iloc[0, 7:23].tolist()

print("Anos de coleta:")
print(anos)

Anos de coleta:
['08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23']

In [ ]:
# Monta os nomes corretos das 24 colunas
novos_nomes = (
    list(df_censo.columns[:7])
    + anos
    + ["Notas Importantes"]
)

df_censo.columns = novos_nomes

print("Quantidade de colunas:", len(df_censo.columns))

print("\nColunas:")
for coluna in df_censo.columns:
    print(f"- {coluna}")

Quantidade de colunas: 24

Colunas:
- N
- Nome da Variável
- Descrição da Variável
- Tipo
- Tam.(1)
- Categoria
- Coleta por ano ("s"=sim;"n"=não )
- 08
- 09
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- Notas Importantes

In [ ]:
df_censo.head(10)

,N,Nome da Variável,Descrição da Variável,Tipo,Tam.(1),Categoria,"Coleta por ano (""s""=sim;""n""=não )",08,09,10,...,15,16,17,18,19,20,21,22,23,Notas Importantes
0,NaN,NaN,NaN,NaN,NaN,NaN,07,08,09,10,...,15,16,17,18,19,20,21,22,23,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,NU_ANO_CENSO,Ano do Censo,Num,4.0,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN
3,2,NO_REGIAO,Nome da Região Geográfica,Char,20.0,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN
4,3,CO_REGIAO,Código da Região Geográfica,Num,1.0,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN
5,4,NO_UF,Nome da Unidade da Federação,Char,50.0,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN
6,5,SG_UF,Sigla da Unidade da Federação,Char,2.0,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN
7,6,CO_UF,Código da Unidade da Federação,Num,2.0,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN
8,7,NO_MUNICIPIO,Nome do Município,Char,150.0,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN
9,8,CO_MUNICIPIO,Código do Município,Num,7.0,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN

In [ ]:
inventario_censo = df_censo[
    ["N", "Nome da Variável", "Descrição da Variável", "Tipo", "Tam.(1)", "Categoria"]
].copy()

print("Quantidade de variáveis:", len(inventario_censo))

inventario_censo.head(20)

Quantidade de variáveis: 465

,N,Nome da Variável,Descrição da Variável,Tipo,Tam.(1),Categoria
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,1,NU_ANO_CENSO,Ano do Censo,Num,4.0,NaN
3,2,NO_REGIAO,Nome da Região Geográfica,Char,20.0,NaN
4,3,CO_REGIAO,Código da Região Geográfica,Num,1.0,NaN
5,4,NO_UF,Nome da Unidade da Federação,Char,50.0,NaN
6,5,SG_UF,Sigla da Unidade da Federação,Char,2.0,NaN
7,6,CO_UF,Código da Unidade da Federação,Num,2.0,NaN
8,7,NO_MUNICIPIO,Nome do Município,Char,150.0,NaN
9,8,CO_MUNICIPIO,Código do Município,Num,7.0,NaN
10,9,NO_REGIAO_GEOG_INTERM,Nome da Região Geográfica Intermediária,Char,100.0,NaN
11,10,CO_REGIAO_GEOG_INTERM,Código da Região Geográfica Intermediária,Num,4.0,NaN
12,11,NO_REGIAO_GEOG_IMED,Nome da Região Geográfica Imediata,Char,100.0,NaN
13,12,CO_REGIAO_GEOG_IMED,Código da Região Geográfica Imediata,Num,6.0,NaN
14,13,NO_MESORREGIAO,Nome da Mesorregião,Char,100.0,NaN
15,14,CO_MESORREGIAO,Código da Mesorregião,Num,4.0,NaN
16,15,NO_MICRORREGIAO,Nome da Microrregião,Char,100.0,NaN
17,16,CO_MICRORREGIAO,Código da Microrregião,Num,5.0,NaN
18,17,CO_DISTRITO,Código completo do Distrito da escola,Num,9.0,NaN
19,18,NO_ENTIDADE,Nome da Escola,Char,100.0,NaN

In [ ]:
inventario_censo = inventario_censo[
    inventario_censo["N"].notna()
].copy()

print("Quantidade de variáveis:", len(inventario_censo))

Quantidade de variáveis: 462

In [ ]:
linhas_sem_n = df_censo[df_censo["N"].isna()]

print("Linhas sem número de variável:", len(linhas_sem_n))

linhas_sem_n

Linhas sem número de variável: 3

,N,Nome da Variável,Descrição da Variável,Tipo,Tam.(1),Categoria,"Coleta por ano (""s""=sim;""n""=não )",08,09,10,...,15,16,17,18,19,20,21,22,23,Notas Importantes
0,NaN,NaN,NaN,NaN,NaN,NaN,07,08,09,10,...,15,16,17,18,19,20,21,22,23,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Observação sobre a estrutura do dicionário

A aba `microdados_unidade_coleta` possui 465 linhas e 24 colunas no arquivo original.

Durante a leitura, foram identificadas 3 linhas sem número de variável (`N`), utilizadas como elementos estruturais do próprio dicionário.

Considerando apenas os registros que possuem o campo `N` preenchido, foram identificadas **462 variáveis**.

As colunas de anos representam a disponibilidade da variável para coleta entre 2008 e 2023.

In [ ]:
# Inventário completo das variáveis disponíveis no Censo Escolar

print("Total de variáveis:", len(inventario_censo))

display(inventario_censo)

Total de variáveis: 462

,N,Nome da Variável,Descrição da Variável,Tipo,Tam.(1),Categoria
2,1,NU_ANO_CENSO,Ano do Censo,Num,4.0,NaN
3,2,NO_REGIAO,Nome da Região Geográfica,Char,20.0,NaN
4,3,CO_REGIAO,Código da Região Geográfica,Num,1.0,NaN
5,4,NO_UF,Nome da Unidade da Federação,Char,50.0,NaN
6,5,SG_UF,Sigla da Unidade da Federação,Char,2.0,NaN
...,...,...,...,...,...,...
459,458,QT_TUR_MED_INT,Número de Turmas do Ensino Médio - Tempo Integral,Num,8.0,NaN
461,Notas:,NaN,NaN,NaN,NaN,NaN
462,1) Tamanho do campo em termos de caracteres oc...,NaN,NaN,NaN,NaN,NaN
463,"2) De 2020 a 2023, os limites adotados para as...",NaN,NaN,NaN,NaN,NaN
464,"3) Em 2019, os limites adotados para as variáv...",NaN,NaN,NaN,NaN,NaN

In [ ]:
print("Tipos de variáveis:")
print(inventario_censo["Tipo"].value_counts())

Tipos de variáveis:
Tipo
Num     439
Char     17
Data      2
Name: count, dtype: int64

In [ ]:
print("\nCategorias preenchidas:")
print(inventario_censo["Categoria"].notna().sum())

Categorias preenchidas:
284

In [ ]:
tipos_diferentes = inventario_censo[
    ~inventario_censo["Tipo"].isin(["Num", "Char", "Data"])
]

print("Variáveis com tipo diferente ou não informado:", len(tipos_diferentes))

display(
    tipos_diferentes[
        ["N", "Nome da Variável", "Descrição da Variável", "Tipo"]
    ]
)

Variáveis com tipo diferente ou não informado: 4

,N,Nome da Variável,Descrição da Variável,Tipo
461,Notas:,NaN,NaN,NaN
462,1) Tamanho do campo em termos de caracteres oc...,NaN,NaN,NaN
463,"2) De 2020 a 2023, os limites adotados para as...",NaN,NaN,NaN
464,"3) Em 2019, os limites adotados para as variáv...",NaN,NaN,NaN

In [ ]:
inventario_censo = inventario_censo[
    inventario_censo["N"].apply(lambda x: str(x).isdigit())
].copy()

print("Quantidade de variáveis:", len(inventario_censo))

Quantidade de variáveis: 458

In [ ]:
print(inventario_censo["Tipo"].value_counts())

Tipo
Num     439
Char     17
Data      2
Name: count, dtype: int64

**Observação**

O dicionário da aba `microdados_unidade_coleta` apresenta 465 linhas e 24 colunas no arquivo original.

Após considerar apenas os registros com o campo `N` preenchido, foram identificados 462 registros. Desses, 4 correspondem a informações estruturais ou notas do próprio dicionário e não representam variáveis.

Após a exclusão desses registros, o inventário final contém **458 variáveis**.

As colunas referentes aos anos indicam a disponibilidade das variáveis para coleta entre 2008 e 2023.

In [ ]:
inventario_censo = inventario_censo[
    inventario_censo["N"].apply(lambda x: str(x).isdigit())
].copy()

print("Quantidade de variáveis identificadas:", len(inventario_censo))

Quantidade de variáveis identificadas: 458

In [ ]:
print("\nDistribuição dos tipos de variáveis:")
print(inventario_censo["Tipo"].value_counts())

print("\nTotal:", inventario_censo["Tipo"].value_counts().sum())

Distribuição dos tipos de variáveis:
Tipo
Num     439
Char     17
Data      2
Name: count, dtype: int64

Total: 458

In [ ]:
print("Variáveis disponíveis no dicionário:\n")

for _, linha in inventario_censo.iterrows():
    print(f"{int(linha['N']):>3} - {linha['Nome da Variável']}")

Variáveis disponíveis no dicionário:

  1 - NU_ANO_CENSO
  2 - NO_REGIAO
  3 - CO_REGIAO
  4 - NO_UF
  5 - SG_UF
  6 - CO_UF
  7 - NO_MUNICIPIO
  8 - CO_MUNICIPIO
  9 - NO_REGIAO_GEOG_INTERM
 10 - CO_REGIAO_GEOG_INTERM
 11 - NO_REGIAO_GEOG_IMED
 12 - CO_REGIAO_GEOG_IMED
 13 - NO_MESORREGIAO
 14 - CO_MESORREGIAO
 15 - NO_MICRORREGIAO
 16 - CO_MICRORREGIAO
 17 - CO_DISTRITO
 18 - NO_ENTIDADE
 19 - CO_ENTIDADE
 20 - TP_DEPENDENCIA
 21 - TP_CATEGORIA_ESCOLA_PRIVADA
 22 - TP_LOCALIZACAO
 23 - TP_LOCALIZACAO_DIFERENCIADA
 24 - DS_ENDERECO
 25 - NU_ENDERECO
 26 - DS_COMPLEMENTO
 27 - NO_BAIRRO
 28 - CO_CEP
 29 - NU_DDD
 30 - NU_TELEFONE
 31 - TP_SITUACAO_FUNCIONAMENTO
 32 - CO_ORGAO_REGIONAL
 33 - DT_ANO_LETIVO_INICIO
 34 - DT_ANO_LETIVO_TERMINO
 35 - IN_VINCULO_SECRETARIA_EDUCACAO
 36 - IN_VINCULO_SEGURANCA_PUBLICA
 37 - IN_VINCULO_SECRETARIA_SAUDE
 38 - IN_VINCULO_OUTRO_ORGAO
 39 - IN_PODER_PUBLICO_PARCERIA
 40 - TP_PODER_PUBLICO_PARCERIA
 41 - IN_CONVENIADA_PP
 42 - TP_CONVENIO_PODER_PUBLICO
 43 - IN_FORMA_CONT_TERMO_COLABORA
 44 - IN_FORMA_CONT_TERMO_FOMENTO
 45 - IN_FORMA_CONT_ACORDO_COOP
 46 - IN_FORMA_CONT_PRESTACAO_SERV
 47 - IN_FORMA_CONT_COOP_TEC_FIN
 48 - IN_FORMA_CONT_CONSORCIO_PUB
 49 - IN_FORMA_CONT_MU_TERMO_COLAB
 50 - IN_FORMA_CONT_MU_TERMO_FOMENTO
 51 - IN_FORMA_CONT_MU_ACORDO_COOP
 52 - IN_FORMA_CONT_MU_PREST_SERV
 53 - IN_FORMA_CONT_MU_COOP_TEC_FIN
 54 - IN_FORMA_CONT_MU_CONSORCIO_PUB
 55 - IN_FORMA_CONT_ES_TERMO_COLAB
 56 - IN_FORMA_CONT_ES_TERMO_FOMENTO
 57 - IN_FORMA_CONT_ES_ACORDO_COOP
 58 - IN_FORMA_CONT_ES_PREST_SERV
 59 - IN_FORMA_CONT_ES_COOP_TEC_FIN
 60 - IN_FORMA_CONT_ES_CONSORCIO_PUB
 61 - IN_TIPO_ATEND_ESCOLARIZACAO
 62 - IN_TIPO_ATEND_AC
 63 - IN_TIPO_ATEND_AEE
 64 - IN_MANT_ESCOLA_PRIVADA_EMP
 65 - IN_MANT_ESCOLA_PRIVADA_ONG
 66 - IN_MANT_ESCOLA_PRIVADA_OSCIP
 67 - IN_MANT_ESCOLA_PRIV_ONG_OSCIP
 68 - IN_MANT_ESCOLA_PRIVADA_SIND
 69 - IN_MANT_ESCOLA_PRIVADA_SIST_S
 70 - IN_MANT_ESCOLA_PRIVADA_S_FINS
 71 - NU_CNPJ_ESCOLA_PRIVADA
 72 - NU_CNPJ_MANTENEDORA
 73 - TP_REGULAMENTACAO
 74 - TP_RESPONSAVEL_REGULAMENTACAO
 75 - CO_ESCOLA_SEDE_VINCULADA
 76 - CO_IES_OFERTANTE
 77 - IN_LOCAL_FUNC_PREDIO_ESCOLAR
 78 - TP_OCUPACAO_PREDIO_ESCOLAR
 79 - IN_LOCAL_FUNC_SALAS_EMPRESA
 80 - IN_LOCAL_FUNC_SOCIOEDUCATIVO
 81 - IN_LOCAL_FUNC_UNID_PRISIONAL
 82 - IN_LOCAL_FUNC_PRISIONAL_SOCIO
 83 - IN_LOCAL_FUNC_TEMPLO_IGREJA
 84 - IN_LOCAL_FUNC_CASA_PROFESSOR
 85 - IN_LOCAL_FUNC_GALPAO
 86 - TP_OCUPACAO_GALPAO
 87 - IN_LOCAL_FUNC_SALAS_OUTRA_ESC
 88 - IN_LOCAL_FUNC_OUTROS
 89 - IN_PREDIO_COMPARTILHADO
 90 - IN_AGUA_FILTRADA
 91 - IN_AGUA_POTAVEL
 92 - IN_AGUA_REDE_PUBLICA
 93 - IN_AGUA_POCO_ARTESIANO
 94 - IN_AGUA_CACIMBA
 95 - IN_AGUA_FONTE_RIO
 96 - IN_AGUA_INEXISTENTE
 97 - IN_ENERGIA_REDE_PUBLICA
 98 - IN_ENERGIA_GERADOR
 99 - IN_ENERGIA_GERADOR_FOSSIL
100 - IN_ENERGIA_OUTROS
101 - IN_ENERGIA_RENOVAVEL
102 - IN_ENERGIA_INEXISTENTE
103 - IN_ESGOTO_REDE_PUBLICA
104 - IN_ESGOTO_FOSSA_SEPTICA
105 - IN_ESGOTO_FOSSA_COMUM
106 - IN_ESGOTO_FOSSA
107 - IN_ESGOTO_INEXISTENTE
108 - IN_LIXO_SERVICO_COLETA
109 - IN_LIXO_QUEIMA
110 - IN_LIXO_ENTERRA
111 - IN_LIXO_DESTINO_FINAL_PUBLICO
112 - IN_LIXO_DESCARTA_OUTRA_AREA
113 - IN_LIXO_JOGA_OUTRA_AREA
114 - IN_LIXO_OUTROS
115 - IN_LIXO_RECICLA
116 - IN_TRATAMENTO_LIXO_SEPARACAO
117 - IN_TRATAMENTO_LIXO_REUTILIZA
118 - IN_TRATAMENTO_LIXO_RECICLAGEM
119 - IN_TRATAMENTO_LIXO_INEXISTENTE
120 - IN_ALMOXARIFADO
121 - IN_AREA_VERDE
122 - IN_AUDITORIO
123 - IN_BANHEIRO_FORA_PREDIO
124 - IN_BANHEIRO_DENTRO_PREDIO
125 - IN_BANHEIRO
126 - IN_BANHEIRO_EI
127 - IN_BANHEIRO_PNE
128 - IN_BANHEIRO_FUNCIONARIOS
129 - IN_BANHEIRO_CHUVEIRO
130 - IN_BERCARIO
131 - IN_BIBLIOTECA
132 - IN_BIBLIOTECA_SALA_LEITURA
133 - IN_COZINHA
134 - IN_DESPENSA
135 - IN_DORMITORIO_ALUNO
136 - IN_DORMITORIO_PROFESSOR
137 - IN_LABORATORIO_CIENCIAS
138 - IN_LABORATORIO_INFORMATICA
139 - IN_LABORATORIO_EDUC_PROF
140 - IN_PATIO_COBERTO
141 - IN_PATIO_DESCOBERTO
142 - IN_PARQUE_INFANTIL
143 - IN_PISCINA
144 - IN_QUADRA_ESPORTES
145 - IN_QUADRA_ESPORTES_COBERTA
146 - IN_QUADRA_ESPORTES_DESCOBERTA
147 - IN_REFEITORIO
148 - IN_SALA_ATELIE_ARTES
149 - IN_SALA_MUSICA_CORAL
150 - IN_SALA_ESTUDIO_DANCA
151 - IN_SALA_MULTIUSO
152 - IN_SALA_ESTUDIO_GRAVACAO
153 - IN_SALA_OFICINAS_EDUC_PROF
154 - IN_SALA_DIRETORIA
155 - IN_SALA_LEITURA
156 - IN_SALA_PROFESSOR
157 - IN_SALA_REPOUSO_ALUNO
158 - IN_SECRETARIA
159 - IN_SALA_ATENDIMENTO_ESPECIAL
160 - IN_TERREIRAO
161 - IN_VIVEIRO
162 - IN_DEPENDENCIAS_PNE
163 - IN_LAVANDERIA
164 - IN_DEPENDENCIAS_OUTRAS
165 - IN_ACESSIBILIDADE_CORRIMAO
166 - IN_ACESSIBILIDADE_ELEVADOR
167 - IN_ACESSIBILIDADE_PISOS_TATEIS
168 - IN_ACESSIBILIDADE_VAO_LIVRE
169 - IN_ACESSIBILIDADE_RAMPAS
170 - IN_ACESSIBILIDADE_SINAL_SONORO
171 - IN_ACESSIBILIDADE_SINAL_TATIL
172 - IN_ACESSIBILIDADE_SINAL_VISUAL
173 - IN_ACESSIBILIDADE_INEXISTENTE
174 - QT_SALAS_EXISTENTES
175 - QT_SALAS_UTILIZADAS_DENTRO
176 - QT_SALAS_UTILIZADAS_FORA
177 - QT_SALAS_UTILIZADAS
178 - QT_SALAS_UTILIZA_CLIMATIZADAS
179 - QT_SALAS_UTILIZADAS_ACESSIVEIS
180 - IN_EQUIP_PARABOLICA
181 - IN_COMPUTADOR
182 - IN_EQUIP_COPIADORA
183 - IN_EQUIP_IMPRESSORA
184 - IN_EQUIP_IMPRESSORA_MULT
185 - IN_EQUIP_SCANNER
186 - IN_EQUIP_NENHUM
187 - IN_EQUIP_DVD
188 - QT_EQUIP_DVD
189 - IN_EQUIP_SOM
190 - QT_EQUIP_SOM
191 - IN_EQUIP_TV
192 - QT_EQUIP_TV
193 - IN_EQUIP_LOUSA_DIGITAL
194 - QT_EQUIP_LOUSA_DIGITAL
195 - IN_EQUIP_MULTIMIDIA
196 - QT_EQUIP_MULTIMIDIA
197 - IN_EQUIP_VIDEOCASSETE
198 - IN_EQUIP_RETROPROJETOR
199 - IN_EQUIP_FAX
200 - IN_EQUIP_FOTO
201 - QT_EQUIP_VIDEOCASSETE
202 - QT_EQUIP_PARABOLICA
203 - QT_EQUIP_COPIADORA
204 - QT_EQUIP_RETROPROJETOR
205 - QT_EQUIP_IMPRESSORA
206 - QT_EQUIP_IMPRESSORA_MULT
207 - QT_EQUIP_FAX
208 - QT_EQUIP_FOTO
209 - QT_COMP_ALUNO
210 - IN_DESKTOP_ALUNO
211 - QT_DESKTOP_ALUNO
212 - IN_COMP_PORTATIL_ALUNO
213 - QT_COMP_PORTATIL_ALUNO
214 - IN_TABLET_ALUNO
215 - QT_TABLET_ALUNO
216 - QT_COMPUTADOR
217 - QT_COMP_ADMINISTRATIVO
218 - IN_INTERNET
219 - IN_INTERNET_ALUNOS
220 - IN_INTERNET_ADMINISTRATIVO
221 - IN_INTERNET_APRENDIZAGEM
222 - IN_INTERNET_COMUNIDADE
223 - IN_ACESSO_INTERNET_COMPUTADOR
224 - IN_ACES_INTERNET_DISP_PESSOAIS
225 - TP_REDE_LOCAL
226 - IN_BANDA_LARGA
227 - QT_FUNCIONARIOS
228 - IN_PROF_ADMINISTRATIVOS
229 - QT_PROF_ADMINISTRATIVOS
230 - IN_PROF_SERVICOS_GERAIS
231 - QT_PROF_SERVICOS_GERAIS
232 - IN_PROF_BIBLIOTECARIO
233 - QT_PROF_BIBLIOTECARIO
234 - IN_PROF_SAUDE
235 - QT_PROF_SAUDE
236 - IN_PROF_COORDENADOR
237 - QT_PROF_COORDENADOR
238 - IN_PROF_FONAUDIOLOGO
239 - QT_PROF_FONAUDIOLOGO
240 - IN_PROF_NUTRICIONISTA
241 - QT_PROF_NUTRICIONISTA
242 - IN_PROF_PSICOLOGO
243 - QT_PROF_PSICOLOGO
244 - IN_PROF_ALIMENTACAO
245 - QT_PROF_ALIMENTACAO
246 - IN_PROF_PEDAGOGIA
247 - QT_PROF_PEDAGOGIA
248 - IN_PROF_SECRETARIO
249 - QT_PROF_SECRETARIO
250 - IN_PROF_SEGURANCA
251 - QT_PROF_SEGURANCA
252 - IN_PROF_MONITORES
253 - QT_PROF_MONITORES
254 - IN_PROF_GESTAO
255 - QT_PROF_GESTAO
256 - IN_PROF_ASSIST_SOCIAL
257 - QT_PROF_ASSIST_SOCIAL
258 - IN_PROF_TRAD_LIBRAS
259 - QT_PROF_TRAD_LIBRAS
260 - IN_ALIMENTACAO
261 - IN_SERIE_ANO
262 - IN_PERIODOS_SEMESTRAIS
263 - IN_FUNDAMENTAL_CICLOS
264 - IN_GRUPOS_NAO_SERIADOS
265 - IN_MODULOS
266 - IN_FORMACAO_ALTERNANCIA
267 - IN_MATERIAL_PED_MULTIMIDIA
268 - IN_MATERIAL_PED_INFANTIL
269 - IN_MATERIAL_PED_CIENTIFICO
270 - IN_MATERIAL_PED_DIFUSAO
271 - IN_MATERIAL_PED_MUSICAL
272 - IN_MATERIAL_PED_JOGOS
273 - IN_MATERIAL_PED_ARTISTICAS
274 - IN_MATERIAL_PED_PROFISSIONAL
275 - IN_MATERIAL_PED_DESPORTIVA
276 - IN_MATERIAL_PED_INDIGENA
277 - IN_MATERIAL_PED_ETNICO
278 - IN_MATERIAL_PED_CAMPO
279 - IN_MATERIAL_PED_BIL_SURDOS
280 - IN_MATERIAL_PED_NENHUM
281 - IN_MATERIAL_ESP_QUILOMBOLA
282 - IN_MATERIAL_ESP_INDIGENA
283 - IN_MATERIAL_ESP_NAO_UTILIZA
284 - IN_EDUCACAO_INDIGENA
285 - TP_INDIGENA_LINGUA
286 - CO_LINGUA_INDIGENA_1
287 - CO_LINGUA_INDIGENA_2
288 - CO_LINGUA_INDIGENA_3
289 - IN_BRASIL_ALFABETIZADO
290 - IN_FINAL_SEMANA
291 - IN_EXAME_SELECAO
292 - IN_RESERVA_PPI
293 - IN_RESERVA_RENDA
294 - IN_RESERVA_PUBLICA
295 - IN_RESERVA_PCD
296 - IN_RESERVA_OUTROS
297 - IN_RESERVA_NENHUMA
298 - IN_REDES_SOCIAIS
299 - IN_ESPACO_ATIVIDADE
300 - IN_ESPACO_EQUIPAMENTO
301 - IN_ORGAO_ASS_PAIS
302 - IN_ORGAO_ASS_PAIS_MESTRES
303 - IN_ORGAO_CONSELHO_ESCOLAR
304 - IN_ORGAO_GREMIO_ESTUDANTIL
305 - IN_ORGAO_OUTROS
306 - IN_ORGAO_NENHUM
307 - TP_PROPOSTA_PEDAGOGICA
308 - TP_AEE
309 - TP_ATIVIDADE_COMPLEMENTAR
310 - IN_MEDIACAO_PRESENCIAL
311 - IN_MEDIACAO_SEMIPRESENCIAL
312 - IN_MEDIACAO_EAD
313 - IN_REGULAR
314 - IN_DIURNO
315 - IN_NOTURNO
316 - IN_EAD
317 - IN_BAS
318 - IN_ESCOLARIZACAO
319 - IN_INF
320 - IN_INF_CRE
321 - IN_INF_PRE
322 - IN_FUND
323 - IN_FUND_AI
324 - IN_FUND_AF
325 - IN_MED
326 - IN_PROF
327 - IN_PROF_TEC
328 - IN_EJA
329 - IN_EJA_FUND
330 - IN_EJA_MED
331 - IN_ESP
332 - IN_ESP_CC
333 - IN_ESP_CE
334 - QT_MAT_BAS
335 - QT_MAT_INF
336 - QT_MAT_INF_CRE
337 - QT_MAT_INF_PRE
338 - QT_MAT_FUND
339 - QT_MAT_FUND_AI
340 - QT_MAT_FUND_AI_1
341 - QT_MAT_FUND_AI_2
342 - QT_MAT_FUND_AI_3
343 - QT_MAT_FUND_AI_4
344 - QT_MAT_FUND_AI_5
345 - QT_MAT_FUND_AF
346 - QT_MAT_FUND_AF_6
347 - QT_MAT_FUND_AF_7
348 - QT_MAT_FUND_AF_8
349 - QT_MAT_FUND_AF_9
350 - QT_MAT_MED
351 - QT_MAT_MED_PROP
352 - QT_MAT_MED_PROP_1
353 - QT_MAT_MED_PROP_2
354 - QT_MAT_MED_PROP_3
355 - QT_MAT_MED_PROP_4
356 - QT_MAT_MED_PROP_NS
357 - QT_MAT_MED_CT
358 - QT_MAT_MED_CT_1
359 - QT_MAT_MED_CT_2
360 - QT_MAT_MED_CT_3
361 - QT_MAT_MED_CT_4
362 - QT_MAT_MED_CT_NS
363 - QT_MAT_MED_NM
364 - QT_MAT_MED_NM_1
365 - QT_MAT_MED_NM_2
366 - QT_MAT_MED_NM_3
367 - QT_MAT_MED_NM_4
368 - QT_MAT_PROF
369 - QT_MAT_PROF_TEC
370 - QT_MAT_PROF_TEC_CONC
371 - QT_MAT_PROF_TEC_SUBS
372 - QT_MAT_PROF_FIC_CONC
373 - QT_MAT_EJA
374 - QT_MAT_EJA_FUND
375 - QT_MAT_EJA_FUND_AI
376 - QT_MAT_EJA_FUND_AF
377 - QT_MAT_EJA_FUND_PJ
378 - QT_MAT_EJA_FUND_AIAF
379 - QT_MAT_EJA_FUND_FIC
380 - QT_MAT_EJA_MED
381 - QT_MAT_EJA_MED_NPROF
382 - QT_MAT_EJA_MED_FIC
383 - QT_MAT_EJA_MED_TEC
384 - QT_MAT_ESP
385 - QT_MAT_ESP_CC
386 - QT_MAT_ESP_CE
387 - QT_MAT_BAS_FEM
388 - QT_MAT_BAS_MASC
389 - QT_MAT_BAS_ND
390 - QT_MAT_BAS_BRANCA
391 - QT_MAT_BAS_PRETA
392 - QT_MAT_BAS_PARDA
393 - QT_MAT_BAS_AMARELA
394 - QT_MAT_BAS_INDIGENA
395 - QT_MAT_BAS_0_3
396 - QT_MAT_BAS_4_5
397 - QT_MAT_BAS_6_10
398 - QT_MAT_BAS_11_14
399 - QT_MAT_BAS_15_17
400 - QT_MAT_BAS_18_MAIS
401 - QT_MAT_BAS_D
402 - QT_MAT_BAS_N
403 - QT_MAT_BAS_EAD
404 - QT_MAT_INF_INT
405 - QT_MAT_INF_CRE_INT
406 - QT_MAT_INF_PRE_INT
407 - QT_MAT_FUND_INT
408 - QT_MAT_FUND_AI_INT
409 - QT_MAT_FUND_AF_INT
410 - QT_MAT_MED_INT
411 - QT_MAT_ZR_URB
412 - QT_MAT_ZR_RUR
413 - QT_MAT_ZR_NA
414 - QT_TRANSP_PUBLICO
415 - QT_TRANSP_RESP_EST
416 - QT_TRANSP_RESP_MUN
417 - QT_DOC_BAS
418 - QT_DOC_INF
419 - QT_DOC_INF_CRE
420 - QT_DOC_INF_PRE
421 - QT_DOC_FUND
422 - QT_DOC_FUND_AI
423 - QT_DOC_FUND_AF
424 - QT_DOC_MED
425 - QT_DOC_PROF
426 - QT_DOC_PROF_TEC
427 - QT_DOC_EJA
428 - QT_DOC_EJA_FUND
429 - QT_DOC_EJA_MED
430 - QT_DOC_ESP
431 - QT_DOC_ESP_CC
432 - QT_DOC_ESP_CE
433 - QT_TUR_BAS
434 - QT_TUR_INF
435 - QT_TUR_INF_CRE
436 - QT_TUR_INF_PRE
437 - QT_TUR_FUND
438 - QT_TUR_FUND_AI
439 - QT_TUR_FUND_AF
440 - QT_TUR_MED
441 - QT_TUR_PROF
442 - QT_TUR_PROF_TEC
443 - QT_TUR_EJA
444 - QT_TUR_EJA_FUND
445 - QT_TUR_EJA_MED
446 - QT_TUR_ESP
447 - QT_TUR_ESP_CC
448 - QT_TUR_ESP_CE
449 - QT_TUR_BAS_D
450 - QT_TUR_BAS_N
451 - QT_TUR_BAS_EAD
452 - QT_TUR_INF_INT
453 - QT_TUR_INF_CRE_INT
454 - QT_TUR_INF_PRE_INT
455 - QT_TUR_FUND_INT
456 - QT_TUR_FUND_AI_INT
457 - QT_TUR_FUND_AF_INT
458 - QT_TUR_MED_INT

### 2.3 Análise da estrutura das variáveis

Após a identificação das 458 variáveis, será analisado o padrão de nomenclatura utilizado pelo dicionário do Censo Escolar.

Essa etapa tem como objetivo compreender como as variáveis estão organizadas e quais tipos de informação são disponibilizados, sem realizar ainda a seleção das variáveis que serão utilizadas no projeto

In [ ]:
# Análise dos prefixos utilizados na nomenclatura das variáveis

prefixos = (
    inventario_censo["Nome da Variável"]
    .str.split("_")
    .str[0]
)

print("Quantidade de variáveis por prefixo:\n")
print(prefixos.value_counts())

Quantidade de variáveis por prefixo:

Nome da Variável
IN    239
QT    167
CO     16
TP     16
NO      9
NU      6
DT      2
DS      2
SG      1
Name: count, dtype: int64

Observação sobre a nomenclatura das variáveis

A análise dos nomes das 458 variáveis identificou 9 prefixos distintos:

- `IN`: 239 variáveis
- `QT`: 167 variáveis
- `CO`: 16 variáveis
- `TP`: 16 variáveis
- `NO`: 9 variáveis
- `NU`: 6 variáveis
- `DT`: 2 variáveis
- `DS`: 2 variáveis
- `SG`: 1 variável

Os prefixos `IN` e `QT` concentram a maior parte das variáveis do dicionário, indicando uma predominância de indicadores e informações quantitativas na estrutura analisada.

A classificação foi realizada a partir do padrão de nomenclatura apresentado no próprio nome das variáveis.

In [ ]:
distribuicao_prefixo_tipo = pd.crosstab(
    prefixos,
    inventario_censo["Tipo"]
)

distribuicao_prefixo_tipo

Tipo              Char  Data  Num
Nome da Variável
CO                   2     0   14
DS                   2     0    0
DT                   0     2    0
IN                   0     0  239
NO                   9     0    0
NU                   3     0    3
QT                   0     0  167
SG                   1     0    0
TP                   0     0   16

### 2.4 Padrão de nomenclatura das variáveis

A partir da análise dos nomes e das respectivas descrições apresentadas no dicionário de variáveis do Censo Escolar, foram identificados padrões de nomenclatura associados à natureza das informações.

Os prefixos abaixo foram interpretados com base nos exemplos e descrições presentes no próprio dicionário:

| Prefixo | Interpretação | Exemplo |
|---|---|---|
| `IN` | Indicador | `IN_BIBLIOTECA` |
| `QT` | Quantidade | `QT_SALAS_EXISTENTES` |
| `CO` | Código | `CO_MUNICIPIO` |
| `TP` | Tipo | `TP_DEPENDENCIA` |
| `NO` | Nome | `NO_MUNICIPIO` |
| `NU` | Número | `NU_ANO_CENSO` |
| `DT` | Data | variáveis `DT_` |
| `DS` | Descrição | variáveis `DS_` |
| `SG` | Sigla | `SG_UF` |

> **Observação:** esta classificação representa o padrão de nomenclatura identificado durante a análise do dicionário e não constitui uma alteração ou padronização dos nomes originais das variáveis.

### 2.5 Suplemento de Cursos Técnicos

A segunda estrutura disponibilizada no dicionário do Censo Escolar
2023 corresponde ao `suplemento_cursos_tecnicos`.

Nesta etapa será realizado o levantamento de sua estrutura e das
variáveis disponíveis, seguindo o mesmo procedimento aplicado à
estrutura `microdados_unidade_coleta`.

O objetivo é identificar as informações disponíveis e avaliar sua
possível contribuição para o projeto, sem realizar ainda a seleção
das variáveis que serão utilizadas nas camadas posteriores.

In [ ]:
df_suplemento = pd.read_excel(
    arquivo_dicionario,
    sheet_name="suplemento_cursos_tecnicos",
    header=None
)

print("Linhas:", df_suplemento.shape[0])
print("Colunas:", df_suplemento.shape[1])

Linhas: 47
Colunas: 24

In [ ]:
df_suplemento.head(15)

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,NaN,Alteração de nomenclatura ou metodologia de cá...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Variável nova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Descontinuidade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Dicionário de Variáveis - Tabela de Cursos Téc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,N,Nome da Variável,Descrição da Variável,Tipo,Tam.(1),Categoria,"Coleta por ano (""s""=sim;""n""=não )",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Notas Importantes
7,NaN,NaN,NaN,NaN,NaN,NaN,07,08,09,10,...,15,16,17,18,19,20,21,22,23,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1,NU_ANO_CENSO,Ano do Censo,Num,4,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN
10,2,NO_REGIAO,Nome da Região Geográfica,Char,20,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN
11,3,CO_REGIAO,Código da Região Geográfica,Num,1,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN
12,4,NO_UF,Nome da Unidade da Federação,Char,50,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN
13,5,SG_UF,Sigla da Unidade da Federação,Char,2,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN
14,6,CO_UF,Código da Unidade da Federação,Num,2,NaN,s,s,s,s,...,s,s,s,s,s,s,s,s,s,NaN

In [ ]:
df_suplemento = pd.read_excel(
    arquivo_dicionario,
    sheet_name="suplemento_cursos_tecnicos",
    header=6
)

print("Linhas:", df_suplemento.shape[0])
print("Colunas:", df_suplemento.shape[1])

print("\nColunas:")
for coluna in df_suplemento.columns:
    print(f"- {coluna}")

Linhas: 40
Colunas: 24

Colunas:
- N
- Nome da Variável
- Descrição da Variável
- Tipo
- Tam.(1)
- Categoria
- Coleta por ano ("s"=sim;"n"=não )
- Unnamed: 7
- Unnamed: 8
- Unnamed: 9
- Unnamed: 10
- Unnamed: 11
- Unnamed: 12
- Unnamed: 13
- Unnamed: 14
- Unnamed: 15
- Unnamed: 16
- Unnamed: 17
- Unnamed: 18
- Unnamed: 19
- Unnamed: 20
- Unnamed: 21
- Unnamed: 22
- Notas Importantes

In [ ]:
# Identifica os anos de coleta
anos_suplemento = df_suplemento.iloc[0, 7:23].tolist()

print("Anos de coleta:")
print(anos_suplemento)

Anos de coleta:
['08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23']

In [ ]:
# Renomeia as colunas de anos
novos_nomes_suplemento = (
    list(df_suplemento.columns[:7])
    + anos_suplemento
    + ["Notas Importantes"]
)

df_suplemento.columns = novos_nomes_suplemento

print("Quantidade de colunas:", len(df_suplemento.columns))

print("\nColunas:")
for coluna in df_suplemento.columns:
    print(f"- {coluna}")

Quantidade de colunas: 24

Colunas:
- N
- Nome da Variável
- Descrição da Variável
- Tipo
- Tam.(1)
- Categoria
- Coleta por ano ("s"=sim;"n"=não )
- 08
- 09
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- Notas Importantes

In [ ]:
linhas_sem_n_suplemento = df_suplemento[
    df_suplemento["N"].isna()
]

print(
    "Linhas sem número de variável:",
    len(linhas_sem_n_suplemento)
)

display(linhas_sem_n_suplemento)

Linhas sem número de variável: 3

,N,Nome da Variável,Descrição da Variável,Tipo,Tam.(1),Categoria,"Coleta por ano (""s""=sim;""n""=não )",08,09,10,...,15,16,17,18,19,20,21,22,23,Notas Importantes
0,NaN,NaN,NaN,NaN,NaN,NaN,07,08,09,10,...,15,16,17,18,19,20,21,22,23,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Identifica as linhas que correspondem efetivamente às variáveis
inventario_suplemento = df_suplemento[
    df_suplemento["N"].notna()
].copy()

print("Quantidade de variáveis identificadas:", len(inventario_suplemento))

Quantidade de variáveis identificadas: 37

In [ ]:
# Inventário completo das variáveis do suplemento de cursos técnicos

display(
    inventario_suplemento[
        ["N", "Nome da Variável", "Descrição da Variável", "Tipo", "Tam.(1)", "Categoria"]
    ]
)

,N,Nome da Variável,Descrição da Variável,Tipo,Tam.(1),Categoria
2,1,NU_ANO_CENSO,Ano do Censo,Num,4.0,NaN
3,2,NO_REGIAO,Nome da Região Geográfica,Char,20.0,NaN
4,3,CO_REGIAO,Código da Região Geográfica,Num,1.0,NaN
5,4,NO_UF,Nome da Unidade da Federação,Char,50.0,NaN
6,5,SG_UF,Sigla da Unidade da Federação,Char,2.0,NaN
7,6,CO_UF,Código da Unidade da Federação,Num,2.0,NaN
8,7,NO_MUNICIPIO,Nome do Município,Char,150.0,NaN
9,8,CO_MUNICIPIO,Código do Município,Num,7.0,NaN
10,9,TP_LOCALIZACAO,Localização,Num,1.0,1 - Urbana\n2 - Rural
11,10,TP_LOCALIZACAO_DIFERENCIADA,Localização diferenciada da escola,Num,1.0,0 - A escola não está em área de localização d...
12,11,TP_DEPENDENCIA,Dependência Administrativa,Num,1.0,1 - Federal\n2 - Estadual\n3 - Municipal\n4 - ...
13,12,NO_ENTIDADE,Código da Escola,Num,8.0,NaN
14,13,CO_ENTIDADE,Nome da Escola,Char,100.0,NaN
15,14,NO_AREA_CURSO_PROFISSIONAL,Nome da Área do Curso Técnico,Char,100.0,NaN
16,15,ID_AREA_CURSO_PROFISSIONAL,Código da Área do Curso Técnico,Num,3.0,NaN
17,16,NO_CURSO_EDUC_PROFISSIONAL,Nome do Cursos Técnico,Char,100.0,NaN
18,17,CO_CURSO_EDUC_PROFISSIONAL,Código do Curso Técnico,Num,5.0,NaN
19,18,QT_CURSO_TEC,Número de Cursos Técnicos,Num,8.0,NaN
20,19,QT_MAT_CURSO_TEC,Número de Matrículas em Cursos Técnicos,Num,8.0,NaN
21,20,QT_CURSO_TEC_CT,Número de Cursos Técnicos - Ensino Médio Integ...,Num,8.0,NaN
22,21,QT_MAT_CURSO_TEC_CT,Número de Matrículas em Cursos Técnicos - Ensi...,Num,8.0,NaN
23,22,QT_CURSO_TEC_NM,Número de Cursos Técnicos - Ensino Médio - Mod...,Num,8.0,NaN
24,23,QT_MAT_CURSO_TEC_NM,Número de Matrículas em Cursos Técnicos - Ensi...,Num,8.0,NaN
25,24,QT_CURSO_TEC_CONC,Número de Cursos Técnicos - Educação Profissio...,Num,8.0,NaN
26,25,QT_MAT_CURSO_TEC_CONC,Número de Matrículas em Cursos Técnicos - Educ...,Num,8.0,NaN
27,26,QT_CURSO_TEC_SUBS,Número de Cursos Técnicos - Educação Profissio...,Num,8.0,NaN
28,27,QT_MAT_TEC_SUBS,Número de Matrículas em Cursos Técnicos - Educ...,Num,8.0,NaN
29,28,QT_CURSO_TEC_EJA,Número de Cursos Técnicos - Curso Técnico Inte...,Num,8.0,NaN
30,29,QT_MAT_TEC_EJA,Número de Matrículas em Cursos Técnicos - Curs...,Num,8.0,NaN
32,Notas:,NaN,NaN,NaN,NaN,NaN
33,1) Tamanho do campo em termos de caracteres oc...,NaN,NaN,NaN,NaN,NaN
34,2) O mesmo aluno pode ter mais de uma matrícul...,NaN,NaN,NaN,NaN,NaN
35,3) Não inclui matrículas e nem cursos em turma...,NaN,NaN,NaN,NaN,NaN
36,4) A Educação Profissional Técnica de Nível Mé...,NaN,NaN,NaN,NaN,NaN
37,5) O número de cursos técnicos considera o côm...,NaN,NaN,NaN,NaN,NaN
38,"6) O Ensino Médio - Normal/Magistério, não con...",NaN,NaN,NaN,NaN,NaN
39,7) O mesmo curso técnico pode ser ofertado em ...,NaN,NaN,NaN,NaN,NaN

In [ ]:
print("Tipos de variáveis:")
print(inventario_suplemento["Tipo"].value_counts())

print("\nTotal:", inventario_suplemento["Tipo"].value_counts().sum())

Tipos de variáveis:
Tipo
Num     22
Char     7
Name: count, dtype: int64

Total: 29

In [ ]:
prefixos_suplemento = (
    inventario_suplemento["Nome da Variável"]
    .str.split("_")
    .str[0]
)

print("Quantidade de variáveis por prefixo:\n")
print(prefixos_suplemento.value_counts())

Quantidade de variáveis por prefixo:

Nome da Variável
QT    12
NO     6
CO     5
TP     3
NU     1
SG     1
ID     1
Name: count, dtype: int64

In [ ]:
# Identifica as variáveis que não possuem Tipo informado

variaveis_sem_tipo = inventario_suplemento[
    inventario_suplemento["Tipo"].isna()
]

print("Variáveis sem tipo informado:", len(variaveis_sem_tipo))

display(
    variaveis_sem_tipo[
        ["N", "Nome da Variável", "Descrição da Variável", "Tipo"]
    ]
)

Variáveis sem tipo informado: 8

,N,Nome da Variável,Descrição da Variável,Tipo
32,Notas:,NaN,NaN,NaN
33,1) Tamanho do campo em termos de caracteres oc...,NaN,NaN,NaN
34,2) O mesmo aluno pode ter mais de uma matrícul...,NaN,NaN,NaN
35,3) Não inclui matrículas e nem cursos em turma...,NaN,NaN,NaN
36,4) A Educação Profissional Técnica de Nível Mé...,NaN,NaN,NaN
37,5) O número de cursos técnicos considera o côm...,NaN,NaN,NaN
38,"6) O Ensino Médio - Normal/Magistério, não con...",NaN,NaN,NaN
39,7) O mesmo curso técnico pode ser ofertado em ...,NaN,NaN,NaN

In [ ]:
# Mantém somente as linhas que correspondem às variáveis
inventario_suplemento = inventario_suplemento[
    pd.to_numeric(inventario_suplemento["N"], errors="coerce").notna()
].copy()

print("Quantidade de variáveis identificadas:", len(inventario_suplemento))

Quantidade de variáveis identificadas: 29

Observação sobre a estrutura do dicionário

A aba `suplemento_cursos_tecnicos` possui 40 linhas e 24 colunas após a leitura do arquivo.

Durante a análise da estrutura, foram identificadas:

- 3 linhas estruturais do próprio dicionário;
- 8 linhas finais contendo notas e observações sobre as variáveis.

Após a análise, verificou-se que **29 linhas correspondem efetivamente às variáveis descritas no dicionário**.

As 29 variáveis apresentam informações relacionadas à oferta e às matrículas em cursos técnicos, incluindo identificação geográfica, características dos cursos e quantidades de cursos e matrículas.

In [ ]:
# Análise dos prefixos das variáveis do suplemento

prefixos_suplemento = (
    inventario_suplemento["Nome da Variável"]
    .str.split("_")
    .str[0]
)

print("Quantidade de variáveis por prefixo:\n")
print(prefixos_suplemento.value_counts())

print("\nTotal:", prefixos_suplemento.value_counts().sum())

Quantidade de variáveis por prefixo:

Nome da Variável
QT    12
NO     6
CO     5
TP     3
NU     1
SG     1
ID     1
Name: count, dtype: int64

Total: 29

Observação sobre a nomenclatura das variáveis

A análise das 29 variáveis do `suplemento_cursos_tecnicos` identificou 7 prefixos distintos:

- `QT`: 12 variáveis
- `NO`: 6 variáveis
- `CO`: 5 variáveis
- `TP`: 3 variáveis
- `NU`: 1 variável
- `SG`: 1 variável
- `ID`: 1 variável

Os prefixos `QT`, `NO` e `CO` concentram a maior parte das variáveis dessa estrutura, refletindo a presença de informações quantitativas, nomes e códigos relacionados aos cursos técnicos.

A classificação foi realizada a partir do padrão de nomenclatura apresentado no próprio dicionário.

In [ ]:
# Lista completa das variáveis do suplemento de cursos técnicos

print("Variáveis disponíveis no suplemento:\n")

for _, linha in inventario_suplemento.iterrows():
    print(f"{int(linha['N']):>2} - {linha['Nome da Variável']}")

Variáveis disponíveis no suplemento:

 1 - NU_ANO_CENSO
 2 - NO_REGIAO
 3 - CO_REGIAO
 4 - NO_UF
 5 - SG_UF
 6 - CO_UF
 7 - NO_MUNICIPIO
 8 - CO_MUNICIPIO
 9 - TP_LOCALIZACAO
10 - TP_LOCALIZACAO_DIFERENCIADA
11 - TP_DEPENDENCIA
12 - NO_ENTIDADE
13 - CO_ENTIDADE
14 - NO_AREA_CURSO_PROFISSIONAL
15 - ID_AREA_CURSO_PROFISSIONAL
16 - NO_CURSO_EDUC_PROFISSIONAL
17 - CO_CURSO_EDUC_PROFISSIONAL
18 - QT_CURSO_TEC
19 - QT_MAT_CURSO_TEC
20 - QT_CURSO_TEC_CT
21 - QT_MAT_CURSO_TEC_CT
22 - QT_CURSO_TEC_NM
23 - QT_MAT_CURSO_TEC_NM
24 - QT_CURSO_TEC_CONC
25 - QT_MAT_CURSO_TEC_CONC
26 - QT_CURSO_TEC_SUBS
27 - QT_MAT_TEC_SUBS
28 - QT_CURSO_TEC_EJA
29 - QT_MAT_TEC_EJA

Observação sobre o suplemento de cursos técnicos

O `suplemento_cursos_tecnicos` possui 29 variáveis.

A estrutura apresenta variáveis de identificação geográfica e da unidade escolar, como ano do Censo, região, UF, município e entidade, além de variáveis específicas relacionadas à educação profissional técnica.

Entre as informações específicas estão a identificação das áreas e cursos técnicos e as quantidades de cursos e matrículas, incluindo diferentes formas de oferta, como Ensino Médio Integrado, concomitante, subsequente e EJA.

Dessa forma, o suplemento complementa as informações da estrutura `microdados_unidade_coleta` com dados específicos sobre a oferta de cursos técnicos.

Padrão de nomenclatura das variáveis do suplemento

A partir da análise dos nomes e das respectivas descrições apresentadas no dicionário de variáveis do Censo Escolar, foram identificados padrões de nomenclatura associados à natureza das informações.

Os prefixos abaixo foram interpretados com base nos exemplos e descrições presentes no próprio dicionário:

| Prefixo | Interpretação | Exemplo |
|---|---|---|
| `IN` | Indicador | `IN_BIBLIOTECA` |
| `QT` | Quantidade | `QT_SALAS_EXISTENTES` |
| `CO` | Código | `CO_MUNICIPIO` |
| `TP` | Tipo | `TP_DEPENDENCIA` |
| `NO` | Nome | `NO_MUNICIPIO` |
| `NU` | Número | `NU_ANO_CENSO` |
| `DT` | Data | Variáveis `DT_` |
| `DS` | Descrição | Variáveis `DS_` |
| `SG` | Sigla | `SG_UF` |
| `ID` | Identificador | `ID_AREA_CURSO_PROFISSIONAL` |

> **Observação:** esta classificação representa o padrão de nomenclatura identificado durante a análise do dicionário e não constitui uma alteração ou padronização dos nomes originais das variáveis.

In [ ]:
print("Tipos de variáveis:")
print(inventario_suplemento["Tipo"].value_counts())

print("\nTotal:", inventario_suplemento["Tipo"].value_counts().sum())

Tipos de variáveis:
Tipo
Num     22
Char     7
Name: count, dtype: int64

Total: 29

In [ ]:
print("Quantidade de variáveis:", len(inventario_suplemento))

Quantidade de variáveis: 29

Síntese da estrutura `suplemento_cursos_tecnicos`

Após a análise da estrutura do dicionário, foram identificadas **29 variáveis** efetivamente descritas.

A distribuição dos tipos de variáveis é:

- **22 variáveis numéricas (`Num`)**
- **7 variáveis de caracteres (`Char`)**

A estrutura apresenta informações de identificação geográfica e das unidades escolares, além de informações específicas sobre a educação profissional técnica, incluindo áreas, cursos, quantidade de cursos e matrículas por modalidade de oferta.

A análise também identificou 7 padrões de nomenclatura (`QT`, `NO`, `CO`, `TP`, `NU`, `SG` e `ID`), utilizados para caracterizar as informações disponíveis no dicionário.

### 2.6 Síntese do Censo Escolar

| Estrutura | Variáveis | Principais informações |
|---|---:|---|
| `microdados_unidade_coleta` | 458 | Características das unidades escolares, localização, infraestrutura, equipamentos, acessibilidade, profissionais e organização escolar. |
| `suplemento_cursos_tecnicos` | 29 | Informações específicas sobre educação profissional técnica, incluindo áreas, cursos, oferta e matrículas. |
| **Total** | **487** | — |

Observação

A análise das duas estruturas resultou em **487 variáveis** documentadas, sendo 458 da estrutura `microdados_unidade_coleta` e 29 do `suplemento_cursos_tecnicos`.

A seleção das variáveis que serão utilizadas nas etapas posteriores não é realizada neste notebook. Este levantamento tem como objetivo documentar as informações disponibilizadas pelas fontes e subsidiar as etapas de definição das análises e das camadas posteriores do projeto.

## Inventário do Censo Escolar 2023

In [ ]:
# Inventário consolidado — Censo Escolar 2023

inventario_censo_geral = pd.concat([
    inventario_censo[["Nome da Variável", "Tipo"]].assign(
        Estrutura="microdados_unidade_coleta"
    ),
    inventario_suplemento[["Nome da Variável", "Tipo"]].assign(
        Estrutura="suplemento_cursos_tecnicos"
    )
], ignore_index=True)

inventario_censo_geral["Tipo"] = inventario_censo_geral["Tipo"].replace({
    "Char": "String"
})

inventario_censo_geral = inventario_censo_geral[
    ["Estrutura", "Nome da Variável", "Tipo"]
]

pd.set_option("display.max_rows", None)

display(inventario_censo_geral)

                      Estrutura                Nome da Variável    Tipo
0     microdados_unidade_coleta                    NU_ANO_CENSO     Num
1     microdados_unidade_coleta                       NO_REGIAO  String
2     microdados_unidade_coleta                       CO_REGIAO     Num
3     microdados_unidade_coleta                           NO_UF  String
4     microdados_unidade_coleta                           SG_UF  String
5     microdados_unidade_coleta                           CO_UF     Num
6     microdados_unidade_coleta                    NO_MUNICIPIO  String
7     microdados_unidade_coleta                    CO_MUNICIPIO     Num
8     microdados_unidade_coleta           NO_REGIAO_GEOG_INTERM  String
9     microdados_unidade_coleta           CO_REGIAO_GEOG_INTERM     Num
10    microdados_unidade_coleta             NO_REGIAO_GEOG_IMED  String
11    microdados_unidade_coleta             CO_REGIAO_GEOG_IMED     Num
12    microdados_unidade_coleta                  NO_MESORREGIAO  String
13    microdados_unidade_coleta                  CO_MESORREGIAO     Num
14    microdados_unidade_coleta                 NO_MICRORREGIAO  String
15    microdados_unidade_coleta                 CO_MICRORREGIAO     Num
16    microdados_unidade_coleta                     CO_DISTRITO     Num
17    microdados_unidade_coleta                     NO_ENTIDADE  String
18    microdados_unidade_coleta                     CO_ENTIDADE     Num
19    microdados_unidade_coleta                  TP_DEPENDENCIA     Num
20    microdados_unidade_coleta     TP_CATEGORIA_ESCOLA_PRIVADA     Num
21    microdados_unidade_coleta                  TP_LOCALIZACAO     Num
22    microdados_unidade_coleta     TP_LOCALIZACAO_DIFERENCIADA     Num
23    microdados_unidade_coleta                     DS_ENDERECO  String
24    microdados_unidade_coleta                     NU_ENDERECO  String
25    microdados_unidade_coleta                  DS_COMPLEMENTO  String
26    microdados_unidade_coleta                       NO_BAIRRO  String
27    microdados_unidade_coleta                          CO_CEP  String
28    microdados_unidade_coleta                          NU_DDD     Num
29    microdados_unidade_coleta                     NU_TELEFONE     Num
30    microdados_unidade_coleta       TP_SITUACAO_FUNCIONAMENTO     Num
31    microdados_unidade_coleta               CO_ORGAO_REGIONAL  String
32    microdados_unidade_coleta            DT_ANO_LETIVO_INICIO    Data
33    microdados_unidade_coleta           DT_ANO_LETIVO_TERMINO    Data
34    microdados_unidade_coleta  IN_VINCULO_SECRETARIA_EDUCACAO     Num
35    microdados_unidade_coleta    IN_VINCULO_SEGURANCA_PUBLICA     Num
36    microdados_unidade_coleta     IN_VINCULO_SECRETARIA_SAUDE     Num
37    microdados_unidade_coleta          IN_VINCULO_OUTRO_ORGAO     Num
38    microdados_unidade_coleta       IN_PODER_PUBLICO_PARCERIA     Num
39    microdados_unidade_coleta       TP_PODER_PUBLICO_PARCERIA     Num
40    microdados_unidade_coleta                IN_CONVENIADA_PP     Num
41    microdados_unidade_coleta       TP_CONVENIO_PODER_PUBLICO     Num
42    microdados_unidade_coleta    IN_FORMA_CONT_TERMO_COLABORA     Num
43    microdados_unidade_coleta     IN_FORMA_CONT_TERMO_FOMENTO     Num
44    microdados_unidade_coleta       IN_FORMA_CONT_ACORDO_COOP     Num
45    microdados_unidade_coleta    IN_FORMA_CONT_PRESTACAO_SERV     Num
46    microdados_unidade_coleta      IN_FORMA_CONT_COOP_TEC_FIN     Num
47    microdados_unidade_coleta     IN_FORMA_CONT_CONSORCIO_PUB     Num
48    microdados_unidade_coleta    IN_FORMA_CONT_MU_TERMO_COLAB     Num
49    microdados_unidade_coleta  IN_FORMA_CONT_MU_TERMO_FOMENTO     Num
50    microdados_unidade_coleta    IN_FORMA_CONT_MU_ACORDO_COOP     Num
51    microdados_unidade_coleta     IN_FORMA_CONT_MU_PREST_SERV     Num
52    microdados_unidade_coleta   IN_FORMA_CONT_MU_COOP_TEC_FIN     Num
53    microdados_unidade_coleta  IN_FORMA_CONT_MU_CONSORCIO_PUB     Num
54    microdados_unidade_coleta    IN_FORMA_CONT_ES_TERMO_COLAB     Num
55    microdados_unidade_coleta  IN_FORMA_CONT_ES_TERMO_FOMENTO     Num
56    microdados_unidade_coleta    IN_FORMA_CONT_ES_ACORDO_COOP     Num
57    microdados_unidade_coleta     IN_FORMA_CONT_ES_PREST_SERV     Num
58    microdados_unidade_coleta   IN_FORMA_CONT_ES_COOP_TEC_FIN     Num
59    microdados_unidade_coleta  IN_FORMA_CONT_ES_CONSORCIO_PUB     Num
60    microdados_unidade_coleta     IN_TIPO_ATEND_ESCOLARIZACAO     Num
61    microdados_unidade_coleta                IN_TIPO_ATEND_AC     Num
62    microdados_unidade_coleta               IN_TIPO_ATEND_AEE     Num
63    microdados_unidade_coleta      IN_MANT_ESCOLA_PRIVADA_EMP     Num
64    microdados_unidade_coleta      IN_MANT_ESCOLA_PRIVADA_ONG     Num
65    microdados_unidade_coleta    IN_MANT_ESCOLA_PRIVADA_OSCIP     Num
66    microdados_unidade_coleta   IN_MANT_ESCOLA_PRIV_ONG_OSCIP     Num
67    microdados_unidade_coleta     IN_MANT_ESCOLA_PRIVADA_SIND     Num
68    microdados_unidade_coleta   IN_MANT_ESCOLA_PRIVADA_SIST_S     Num
69    microdados_unidade_coleta   IN_MANT_ESCOLA_PRIVADA_S_FINS     Num
70    microdados_unidade_coleta          NU_CNPJ_ESCOLA_PRIVADA  String
71    microdados_unidade_coleta             NU_CNPJ_MANTENEDORA  String
72    microdados_unidade_coleta               TP_REGULAMENTACAO     Num
73    microdados_unidade_coleta   TP_RESPONSAVEL_REGULAMENTACAO     Num
74    microdados_unidade_coleta        CO_ESCOLA_SEDE_VINCULADA     Num
75    microdados_unidade_coleta                CO_IES_OFERTANTE     Num
76    microdados_unidade_coleta    IN_LOCAL_FUNC_PREDIO_ESCOLAR     Num
77    microdados_unidade_coleta      TP_OCUPACAO_PREDIO_ESCOLAR     Num
78    microdados_unidade_coleta     IN_LOCAL_FUNC_SALAS_EMPRESA     Num
79    microdados_unidade_coleta    IN_LOCAL_FUNC_SOCIOEDUCATIVO     Num
80    microdados_unidade_coleta    IN_LOCAL_FUNC_UNID_PRISIONAL     Num
81    microdados_unidade_coleta   IN_LOCAL_FUNC_PRISIONAL_SOCIO     Num
82    microdados_unidade_coleta     IN_LOCAL_FUNC_TEMPLO_IGREJA     Num
83    microdados_unidade_coleta    IN_LOCAL_FUNC_CASA_PROFESSOR     Num
84    microdados_unidade_coleta            IN_LOCAL_FUNC_GALPAO     Num
85    microdados_unidade_coleta              TP_OCUPACAO_GALPAO     Num
86    microdados_unidade_coleta   IN_LOCAL_FUNC_SALAS_OUTRA_ESC     Num
87    microdados_unidade_coleta            IN_LOCAL_FUNC_OUTROS     Num
88    microdados_unidade_coleta         IN_PREDIO_COMPARTILHADO     Num
89    microdados_unidade_coleta                IN_AGUA_FILTRADA     Num
90    microdados_unidade_coleta                 IN_AGUA_POTAVEL     Num
91    microdados_unidade_coleta            IN_AGUA_REDE_PUBLICA     Num
92    microdados_unidade_coleta          IN_AGUA_POCO_ARTESIANO     Num
93    microdados_unidade_coleta                 IN_AGUA_CACIMBA     Num
94    microdados_unidade_coleta               IN_AGUA_FONTE_RIO     Num
95    microdados_unidade_coleta             IN_AGUA_INEXISTENTE     Num
96    microdados_unidade_coleta         IN_ENERGIA_REDE_PUBLICA     Num
97    microdados_unidade_coleta              IN_ENERGIA_GERADOR     Num
98    microdados_unidade_coleta       IN_ENERGIA_GERADOR_FOSSIL     Num
99    microdados_unidade_coleta               IN_ENERGIA_OUTROS     Num
100   microdados_unidade_coleta            IN_ENERGIA_RENOVAVEL     Num
101   microdados_unidade_coleta          IN_ENERGIA_INEXISTENTE     Num
102   microdados_unidade_coleta          IN_ESGOTO_REDE_PUBLICA     Num
103   microdados_unidade_coleta         IN_ESGOTO_FOSSA_SEPTICA     Num
104   microdados_unidade_coleta           IN_ESGOTO_FOSSA_COMUM     Num
105   microdados_unidade_coleta                 IN_ESGOTO_FOSSA     Num
106   microdados_unidade_coleta           IN_ESGOTO_INEXISTENTE     Num
107   microdados_unidade_coleta          IN_LIXO_SERVICO_COLETA     Num
108   microdados_unidade_coleta                  IN_LIXO_QUEIMA     Num
109   microdados_unidade_coleta                 IN_LIXO_ENTERRA     Num
110   microdados_unidade_coleta   IN_LIXO_DESTINO_FINAL_PUBLICO     Num
111   microdados_unidade_coleta     IN_LIXO_DESCARTA_OUTRA_AREA     Num
112   microdados_unidade_coleta         IN_LIXO_JOGA_OUTRA_AREA     Num
113   microdados_unidade_coleta                  IN_LIXO_OUTROS     Num
114   microdados_unidade_coleta                 IN_LIXO_RECICLA     Num
115   microdados_unidade_coleta    IN_TRATAMENTO_LIXO_SEPARACAO     Num
116   microdados_unidade_coleta    IN_TRATAMENTO_LIXO_REUTILIZA     Num
117   microdados_unidade_coleta   IN_TRATAMENTO_LIXO_RECICLAGEM     Num
118   microdados_unidade_coleta  IN_TRATAMENTO_LIXO_INEXISTENTE     Num
119   microdados_unidade_coleta                 IN_ALMOXARIFADO     Num
120   microdados_unidade_coleta                   IN_AREA_VERDE     Num
121   microdados_unidade_coleta                    IN_AUDITORIO     Num
122   microdados_unidade_coleta         IN_BANHEIRO_FORA_PREDIO     Num
123   microdados_unidade_coleta       IN_BANHEIRO_DENTRO_PREDIO     Num
124   microdados_unidade_coleta                     IN_BANHEIRO     Num
125   microdados_unidade_coleta                  IN_BANHEIRO_EI     Num
126   microdados_unidade_coleta                 IN_BANHEIRO_PNE     Num
127   microdados_unidade_coleta        IN_BANHEIRO_FUNCIONARIOS     Num
128   microdados_unidade_coleta            IN_BANHEIRO_CHUVEIRO     Num
129   microdados_unidade_coleta                     IN_BERCARIO     Num
130   microdados_unidade_coleta                   IN_BIBLIOTECA     Num
131   microdados_unidade_coleta      IN_BIBLIOTECA_SALA_LEITURA     Num
132   microdados_unidade_coleta                      IN_COZINHA     Num
133   microdados_unidade_coleta                     IN_DESPENSA     Num
134   microdados_unidade_coleta             IN_DORMITORIO_ALUNO     Num
135   microdados_unidade_coleta         IN_DORMITORIO_PROFESSOR     Num
136   microdados_unidade_coleta         IN_LABORATORIO_CIENCIAS     Num
137   microdados_unidade_coleta      IN_LABORATORIO_INFORMATICA     Num
138   microdados_unidade_coleta        IN_LABORATORIO_EDUC_PROF     Num
139   microdados_unidade_coleta                IN_PATIO_COBERTO     Num
140   microdados_unidade_coleta             IN_PATIO_DESCOBERTO     Num
141   microdados_unidade_coleta              IN_PARQUE_INFANTIL     Num
142   microdados_unidade_coleta                      IN_PISCINA     Num
143   microdados_unidade_coleta              IN_QUADRA_ESPORTES     Num
144   microdados_unidade_coleta      IN_QUADRA_ESPORTES_COBERTA     Num
145   microdados_unidade_coleta   IN_QUADRA_ESPORTES_DESCOBERTA     Num
146   microdados_unidade_coleta                   IN_REFEITORIO     Num
147   microdados_unidade_coleta            IN_SALA_ATELIE_ARTES     Num
148   microdados_unidade_coleta            IN_SALA_MUSICA_CORAL     Num
149   microdados_unidade_coleta           IN_SALA_ESTUDIO_DANCA     Num
150   microdados_unidade_coleta                IN_SALA_MULTIUSO     Num
151   microdados_unidade_coleta        IN_SALA_ESTUDIO_GRAVACAO     Num
152   microdados_unidade_coleta      IN_SALA_OFICINAS_EDUC_PROF     Num
153   microdados_unidade_coleta               IN_SALA_DIRETORIA     Num
154   microdados_unidade_coleta                 IN_SALA_LEITURA     Num
155   microdados_unidade_coleta               IN_SALA_PROFESSOR     Num
156   microdados_unidade_coleta           IN_SALA_REPOUSO_ALUNO     Num
157   microdados_unidade_coleta                   IN_SECRETARIA     Num
158   microdados_unidade_coleta    IN_SALA_ATENDIMENTO_ESPECIAL     Num
159   microdados_unidade_coleta                    IN_TERREIRAO     Num
160   microdados_unidade_coleta                      IN_VIVEIRO     Num
161   microdados_unidade_coleta             IN_DEPENDENCIAS_PNE     Num
162   microdados_unidade_coleta                   IN_LAVANDERIA     Num
163   microdados_unidade_coleta          IN_DEPENDENCIAS_OUTRAS     Num
164   microdados_unidade_coleta      IN_ACESSIBILIDADE_CORRIMAO     Num
165   microdados_unidade_coleta      IN_ACESSIBILIDADE_ELEVADOR     Num
166   microdados_unidade_coleta  IN_ACESSIBILIDADE_PISOS_TATEIS     Num
167   microdados_unidade_coleta     IN_ACESSIBILIDADE_VAO_LIVRE     Num
168   microdados_unidade_coleta        IN_ACESSIBILIDADE_RAMPAS     Num
169   microdados_unidade_coleta  IN_ACESSIBILIDADE_SINAL_SONORO     Num
170   microdados_unidade_coleta   IN_ACESSIBILIDADE_SINAL_TATIL     Num
171   microdados_unidade_coleta  IN_ACESSIBILIDADE_SINAL_VISUAL     Num
172   microdados_unidade_coleta   IN_ACESSIBILIDADE_INEXISTENTE     Num
173   microdados_unidade_coleta             QT_SALAS_EXISTENTES     Num
174   microdados_unidade_coleta      QT_SALAS_UTILIZADAS_DENTRO     Num
175   microdados_unidade_coleta        QT_SALAS_UTILIZADAS_FORA     Num
176   microdados_unidade_coleta             QT_SALAS_UTILIZADAS     Num
177   microdados_unidade_coleta   QT_SALAS_UTILIZA_CLIMATIZADAS     Num
178   microdados_unidade_coleta  QT_SALAS_UTILIZADAS_ACESSIVEIS     Num
179   microdados_unidade_coleta             IN_EQUIP_PARABOLICA     Num
180   microdados_unidade_coleta                   IN_COMPUTADOR     Num
181   microdados_unidade_coleta              IN_EQUIP_COPIADORA     Num
182   microdados_unidade_coleta             IN_EQUIP_IMPRESSORA     Num
183   microdados_unidade_coleta        IN_EQUIP_IMPRESSORA_MULT     Num
184   microdados_unidade_coleta                IN_EQUIP_SCANNER     Num
185   microdados_unidade_coleta                 IN_EQUIP_NENHUM     Num
186   microdados_unidade_coleta                    IN_EQUIP_DVD     Num
187   microdados_unidade_coleta                    QT_EQUIP_DVD     Num
188   microdados_unidade_coleta                    IN_EQUIP_SOM     Num
189   microdados_unidade_coleta                    QT_EQUIP_SOM     Num
190   microdados_unidade_coleta                     IN_EQUIP_TV     Num
191   microdados_unidade_coleta                     QT_EQUIP_TV     Num
192   microdados_unidade_coleta          IN_EQUIP_LOUSA_DIGITAL     Num
193   microdados_unidade_coleta          QT_EQUIP_LOUSA_DIGITAL     Num
194   microdados_unidade_coleta             IN_EQUIP_MULTIMIDIA     Num
195   microdados_unidade_coleta             QT_EQUIP_MULTIMIDIA     Num
196   microdados_unidade_coleta           IN_EQUIP_VIDEOCASSETE     Num
197   microdados_unidade_coleta          IN_EQUIP_RETROPROJETOR     Num
198   microdados_unidade_coleta                    IN_EQUIP_FAX     Num
199   microdados_unidade_coleta                   IN_EQUIP_FOTO     Num
200   microdados_unidade_coleta           QT_EQUIP_VIDEOCASSETE     Num
201   microdados_unidade_coleta             QT_EQUIP_PARABOLICA     Num
202   microdados_unidade_coleta              QT_EQUIP_COPIADORA     Num
203   microdados_unidade_coleta          QT_EQUIP_RETROPROJETOR     Num
204   microdados_unidade_coleta             QT_EQUIP_IMPRESSORA     Num
205   microdados_unidade_coleta        QT_EQUIP_IMPRESSORA_MULT     Num
206   microdados_unidade_coleta                    QT_EQUIP_FAX     Num
207   microdados_unidade_coleta                   QT_EQUIP_FOTO     Num
208   microdados_unidade_coleta                   QT_COMP_ALUNO     Num
209   microdados_unidade_coleta                IN_DESKTOP_ALUNO     Num
210   microdados_unidade_coleta                QT_DESKTOP_ALUNO     Num
211   microdados_unidade_coleta          IN_COMP_PORTATIL_ALUNO     Num
212   microdados_unidade_coleta          QT_COMP_PORTATIL_ALUNO     Num
213   microdados_unidade_coleta                 IN_TABLET_ALUNO     Num
214   microdados_unidade_coleta                 QT_TABLET_ALUNO     Num
215   microdados_unidade_coleta                   QT_COMPUTADOR     Num
216   microdados_unidade_coleta          QT_COMP_ADMINISTRATIVO     Num
217   microdados_unidade_coleta                     IN_INTERNET     Num
218   microdados_unidade_coleta              IN_INTERNET_ALUNOS     Num
219   microdados_unidade_coleta      IN_INTERNET_ADMINISTRATIVO     Num
220   microdados_unidade_coleta        IN_INTERNET_APRENDIZAGEM     Num
221   microdados_unidade_coleta          IN_INTERNET_COMUNIDADE     Num
222   microdados_unidade_coleta   IN_ACESSO_INTERNET_COMPUTADOR     Num
223   microdados_unidade_coleta  IN_ACES_INTERNET_DISP_PESSOAIS     Num
224   microdados_unidade_coleta                   TP_REDE_LOCAL     Num
225   microdados_unidade_coleta                  IN_BANDA_LARGA     Num
226   microdados_unidade_coleta                 QT_FUNCIONARIOS     Num
227   microdados_unidade_coleta         IN_PROF_ADMINISTRATIVOS     Num
228   microdados_unidade_coleta         QT_PROF_ADMINISTRATIVOS     Num
229   microdados_unidade_coleta         IN_PROF_SERVICOS_GERAIS     Num
230   microdados_unidade_coleta         QT_PROF_SERVICOS_GERAIS     Num
231   microdados_unidade_coleta           IN_PROF_BIBLIOTECARIO     Num
232   microdados_unidade_coleta           QT_PROF_BIBLIOTECARIO     Num
233   microdados_unidade_coleta                   IN_PROF_SAUDE     Num
234   microdados_unidade_coleta                   QT_PROF_SAUDE     Num
235   microdados_unidade_coleta             IN_PROF_COORDENADOR     Num
236   microdados_unidade_coleta             QT_PROF_COORDENADOR     Num
237   microdados_unidade_coleta            IN_PROF_FONAUDIOLOGO     Num
238   microdados_unidade_coleta            QT_PROF_FONAUDIOLOGO     Num
239   microdados_unidade_coleta           IN_PROF_NUTRICIONISTA     Num
240   microdados_unidade_coleta           QT_PROF_NUTRICIONISTA     Num
241   microdados_unidade_coleta               IN_PROF_PSICOLOGO     Num
242   microdados_unidade_coleta               QT_PROF_PSICOLOGO     Num
243   microdados_unidade_coleta             IN_PROF_ALIMENTACAO     Num
244   microdados_unidade_coleta             QT_PROF_ALIMENTACAO     Num
245   microdados_unidade_coleta               IN_PROF_PEDAGOGIA     Num
246   microdados_unidade_coleta               QT_PROF_PEDAGOGIA     Num
247   microdados_unidade_coleta              IN_PROF_SECRETARIO     Num
248   microdados_unidade_coleta              QT_PROF_SECRETARIO     Num
249   microdados_unidade_coleta               IN_PROF_SEGURANCA     Num
250   microdados_unidade_coleta               QT_PROF_SEGURANCA     Num
251   microdados_unidade_coleta               IN_PROF_MONITORES     Num
252   microdados_unidade_coleta               QT_PROF_MONITORES     Num
253   microdados_unidade_coleta                  IN_PROF_GESTAO     Num
254   microdados_unidade_coleta                  QT_PROF_GESTAO     Num
255   microdados_unidade_coleta           IN_PROF_ASSIST_SOCIAL     Num
256   microdados_unidade_coleta           QT_PROF_ASSIST_SOCIAL     Num
257   microdados_unidade_coleta             IN_PROF_TRAD_LIBRAS     Num
258   microdados_unidade_coleta             QT_PROF_TRAD_LIBRAS     Num
259   microdados_unidade_coleta                  IN_ALIMENTACAO     Num
260   microdados_unidade_coleta                    IN_SERIE_ANO     Num
261   microdados_unidade_coleta          IN_PERIODOS_SEMESTRAIS     Num
262   microdados_unidade_coleta           IN_FUNDAMENTAL_CICLOS     Num
263   microdados_unidade_coleta          IN_GRUPOS_NAO_SERIADOS     Num
264   microdados_unidade_coleta                      IN_MODULOS     Num
265   microdados_unidade_coleta         IN_FORMACAO_ALTERNANCIA     Num
266   microdados_unidade_coleta      IN_MATERIAL_PED_MULTIMIDIA     Num
267   microdados_unidade_coleta        IN_MATERIAL_PED_INFANTIL     Num
268   microdados_unidade_coleta      IN_MATERIAL_PED_CIENTIFICO     Num
269   microdados_unidade_coleta         IN_MATERIAL_PED_DIFUSAO     Num
270   microdados_unidade_coleta         IN_MATERIAL_PED_MUSICAL     Num
271   microdados_unidade_coleta           IN_MATERIAL_PED_JOGOS     Num
272   microdados_unidade_coleta      IN_MATERIAL_PED_ARTISTICAS     Num
273   microdados_unidade_coleta    IN_MATERIAL_PED_PROFISSIONAL     Num
274   microdados_unidade_coleta      IN_MATERIAL_PED_DESPORTIVA     Num
275   microdados_unidade_coleta        IN_MATERIAL_PED_INDIGENA     Num

# 🏫 Fonte Complementar 2 — INSE 2023 — Indicador de Nível Socioeconômico

O INSE 2023 foi incorporado ao projeto como uma fonte externa complementar, não estando entre as fontes originalmente relacionadas na documentação do trabalho.

A inclusão da fonte foi considerada por sua aderência ao contexto educacional e ao recorte temporal de 2023.

O conjunto disponibilizado apresenta informações do Indicador de Nível Socioeconômico em diferentes níveis de agregação: Brasil, Unidades da Federação, municípios e escolas.

In [ ]:
# Upload dos arquivos do INSE 2023

from google.colab import files
import pandas as pd

arquivos = files.upload()

print("\nArquivos carregados:")
for arquivo in arquivos:
    print("-", arquivo)

Saving INSE_2023_brasil.xlsx to INSE_2023_brasil.xlsx
Saving INSE_2023_escolas.xlsx to INSE_2023_escolas.xlsx
Saving INSE_2023_estados.xlsx to INSE_2023_estados.xlsx
Saving INSE_2023_municipios.xlsx to INSE_2023_municipios.xlsx

Arquivos carregados:
- INSE_2023_brasil.xlsx
- INSE_2023_escolas.xlsx
- INSE_2023_estados.xlsx
- INSE_2023_municipios.xlsx

In [ ]:
# Identificação dos arquivos do INSE 2023

arquivos_inse = {
    "Brasil": "INSE_2023_brasil.xlsx",
    "Estados": "INSE_2023_estados.xlsx",
    "Municípios": "INSE_2023_municipios.xlsx",
    "Escolas": "INSE_2023_escolas.xlsx"
}

print("Arquivos identificados:")
for nivel, arquivo in arquivos_inse.items():
    print(f"- {nivel}: {arquivo}")

Arquivos identificados:
- Brasil: INSE_2023_brasil.xlsx
- Estados: INSE_2023_estados.xlsx
- Municípios: INSE_2023_municipios.xlsx
- Escolas: INSE_2023_escolas.xlsx

In [ ]:
# Levantamento inicial da estrutura dos arquivos do INSE 2023

for nivel, arquivo in arquivos_inse.items():

    xls = pd.ExcelFile(arquivo)

    print("\n" + "=" * 70)
    print(f"{nivel.upper()}")
    print("=" * 70)

    print("Abas disponíveis:", xls.sheet_names)

    for aba in xls.sheet_names:
        df_temp = pd.read_excel(arquivo, sheet_name=aba)

        print(
            f"  {aba}: "
            f"{df_temp.shape[0]:,} linhas × "
            f"{df_temp.shape[1]} colunas"
        )

======================================================================
BRASIL
======================================================================
Abas disponíveis: ['INSE_BR_2023', 'Dicionário']
  INSE_BR_2023: 63 linhas × 14 colunas
  Dicionário: 14 linhas × 2 colunas

======================================================================
ESTADOS
======================================================================
Abas disponíveis: ['INSE_UF_2023', 'Dicionário']
  INSE_UF_2023: 1,552 linhas × 17 colunas
  Dicionário: 17 linhas × 2 colunas

======================================================================
MUNICÍPIOS
======================================================================
Abas disponíveis: ['INSE_MUN_2023', 'Dicionário']
  INSE_MUN_2023: 125,741 linhas × 19 colunas
  Dicionário: 19 linhas × 2 colunas

======================================================================
ESCOLAS
======================================================================
Abas disponíveis: ['INSE_ESC_2023', 'Dicionário']
  INSE_ESC_2023: 69,756 linhas × 22 colunas
  Dicionário: 22 linhas × 2 colunas

In [ ]:
# Listagem das variáveis disponíveis nas tabelas do INSE 2023

for nivel, arquivo in arquivos_inse.items():

    xls = pd.ExcelFile(arquivo)

    # Primeira aba = tabela principal
    aba_principal = xls.sheet_names[0]

    df_temp = pd.read_excel(
        arquivo,
        sheet_name=aba_principal
    )

    print("\n" + "=" * 70)
    print(f"{nivel.upper()} - {aba_principal}")
    print("=" * 70)

    print(f"Quantidade de variáveis: {len(df_temp.columns)}")
    print("\nColunas:")

    for coluna in df_temp.columns:
        print(f"- {coluna}")

======================================================================
BRASIL - INSE_BR_2023
======================================================================
Quantidade de variáveis: 14

Colunas:
- NU_ANO_SAEB
- TP_TIPO_REDE
- TP_LOCALIZACAO
- TP_CAPITAL
- QTD_ALUNOS_INSE
- MEDIA_INSE
- PC_NIVEL_1
- PC_NIVEL_2
- PC_NIVEL_3
- PC_NIVEL_4
- PC_NIVEL_5
- PC_NIVEL_6
- PC_NIVEL_7
- PC_NIVEL_8

======================================================================
ESTADOS - INSE_UF_2023
======================================================================
Quantidade de variáveis: 17

Colunas:
- NU_ANO_SAEB
- CO_UF
- SG_UF
- NO_UF
- TP_TIPO_REDE
- TP_LOCALIZACAO
- TP_CAPITAL
- QTD_ALUNOS_INSE
- MEDIA_INSE
- PC_NIVEL_1
- PC_NIVEL_2
- PC_NIVEL_3
- PC_NIVEL_4
- PC_NIVEL_5
- PC_NIVEL_6
- PC_NIVEL_7
- PC_NIVEL_8

======================================================================
MUNICÍPIOS - INSE_MUN_2023
======================================================================
Quantidade de variáveis: 19

Colunas:
- NU_ANO_SAEB
- CO_UF
- SG_UF
- NO_UF
- CO_MUNICIPIO
- NO_MUNICIPIO
- TP_TIPO_REDE
- TP_LOCALIZACAO
- TP_CAPITAL
- QTD_ALUNOS_INSE
- MEDIA_INSE
- PC_NIVEL_1
- PC_NIVEL_2
- PC_NIVEL_3
- PC_NIVEL_4
- PC_NIVEL_5
- PC_NIVEL_6
- PC_NIVEL_7
- PC_NIVEL_8

======================================================================
ESCOLAS - INSE_ESC_2023
======================================================================
Quantidade de variáveis: 22

Colunas:
- NU_ANO_SAEB
- CO_UF
- SG_UF
- NO_UF
- CO_MUNICIPIO
- NO_MUNICIPIO
- ID_ESCOLA
- NO_ESCOLA
- TP_TIPO_REDE
- TP_LOCALIZACAO
- TP_CAPITAL
- QTD_ALUNOS_INSE
- MEDIA_INSE
- INSE_CLASSIFICACAO
- PC_NIVEL_1
- PC_NIVEL_2
- PC_NIVEL_3
- PC_NIVEL_4
- PC_NIVEL_5
- PC_NIVEL_6
- PC_NIVEL_7
- PC_NIVEL_8

In [ ]:
# Leitura dos dicionários das bases do INSE 2023

for nivel, arquivo in arquivos_inse.items():

    dicionario = pd.read_excel(
        arquivo,
        sheet_name="Dicionário"
    )

    print("\n" + "=" * 70)
    print(f"DICIONÁRIO - {nivel.upper()}")
    print("=" * 70)

    print(f"Quantidade de registros: {len(dicionario)}")
    print("\nColunas do dicionário:")

    for coluna in dicionario.columns:
        print(f"- {coluna}")

    display(dicionario)

======================================================================
DICIONÁRIO - BRASIL
======================================================================
Quantidade de registros: 14

Colunas do dicionário:
- Nome
- Descrição

               Nome                                          Descrição
0       NU_ANO_SAEB                           Ano de aplicação do Saeb
1      TP_TIPO_REDE  Dependência Administrativa:\n0 - Total (Federa...
2    TP_LOCALIZACAO  Localização:\n0 - Total (Urbana e Rural)\n1 - ...
3        TP_CAPITAL  Capital / Interior:\n0 - Total (Capital e Inte...
4   QTD_ALUNOS_INSE  Quantidade de Alunos com INSE calculado utiliz...
5        MEDIA_INSE  Média ponderada do Indicador de Nível Socioeco...
6        PC_NIVEL_1  Percentual de alunos da Escola classificados n...
7        PC_NIVEL_2  Percentual de alunos da Escola classificados n...
8        PC_NIVEL_3  Percentual de alunos da Escola classificados n...
9        PC_NIVEL_4  Percentual de alunos da Escola classificados n...
10       PC_NIVEL_5  Percentual de alunos da Escola classificados n...
11       PC_NIVEL_6  Percentual de alunos da Escola classificados n...
12       PC_NIVEL_7  Percentual de alunos da Escola classificados n...
13       PC_NIVEL_8  Percentual de alunos da Escola classificados n...

======================================================================
DICIONÁRIO - ESTADOS
======================================================================
Quantidade de registros: 17

Colunas do dicionário:
- Nome
- Descrição

               Nome                                          Descrição
0       NU_ANO_SAEB                           Ano de aplicação do Saeb
1             CO_UF                     Código da Unidade da Federação
2             SG_UF                      Sigla da Unidade da Federação
3             NO_UF                       Nome da Unidade da Federação
4      TP_TIPO_REDE  Dependência Administrativa:\n0 - Total (Federa...
5    TP_LOCALIZACAO  Localização:\n0 - Total (Urbana e Rural)\n1 - ...
6        TP_CAPITAL  Capital / Interior:\n0 - Total (Capital e Inte...
7   QTD_ALUNOS_INSE  Quantidade de Alunos com INSE calculado utiliz...
8        MEDIA_INSE  Média ponderada do Indicador de Nível Socioeco...
9        PC_NIVEL_1  Percentual de alunos do estrato da UF classifi...
10       PC_NIVEL_2  Percentual de alunos do estrato da UF classifi...
11       PC_NIVEL_3  Percentual de alunos do estrato da UF classifi...
12       PC_NIVEL_4  Percentual de alunos do estrato da UF classifi...
13       PC_NIVEL_5  Percentual de alunos do estrato da UF classifi...
14       PC_NIVEL_6  Percentual de alunos do estrato da UF classifi...
15       PC_NIVEL_7  Percentual de alunos do estrato da UF classifi...
16       PC_NIVEL_8  Percentual de alunos do estrato da UF classifi...

======================================================================
DICIONÁRIO - MUNICÍPIOS
======================================================================
Quantidade de registros: 19

Colunas do dicionário:
- Nome
- Descrição

               Nome                                          Descrição
0       NU_ANO_SAEB                           Ano de aplicação do Saeb
1             CO_UF                     Código da Unidade da Federação
2             SG_UF                      Sigla da Unidade da Federação
3             NO_UF                       Nome da Unidade da Federação
4      CO_MUNICIPIO                                Código do Município
5      NO_MUNICIPIO                                  Nome do Município
6      TP_TIPO_REDE  Dependência Administrativa:\n1 - Federal\n2 - ...
7    TP_LOCALIZACAO  Localização:\n0 - Total (Urbana e Rural)\n1 - ...
8        TP_CAPITAL  Área da Escola (relacionado ao Município):\n1 ...
9   QTD_ALUNOS_INSE  Quantidade de Alunos com INSE calculado utiliz...
10       MEDIA_INSE  Média ponderada do Indicador de Nível Socioeco...
11       PC_NIVEL_1  Percentual de alunos da Escola classificados n...
12       PC_NIVEL_2  Percentual de alunos da Escola classificados n...
13       PC_NIVEL_3  Percentual de alunos da Escola classificados n...
14       PC_NIVEL_4  Percentual de alunos da Escola classificados n...
15       PC_NIVEL_5  Percentual de alunos da Escola classificados n...
16       PC_NIVEL_6  Percentual de alunos da Escola classificados n...
17       PC_NIVEL_7  Percentual de alunos da Escola classificados n...
18       PC_NIVEL_8  Percentual de alunos da Escola classificados n...

======================================================================
DICIONÁRIO - ESCOLAS
======================================================================
Quantidade de registros: 22

Colunas do dicionário:
- Nome
- Descrição

                  Nome                                          Descrição
0          NU_ANO_SAEB                           Ano de aplicação do Saeb
1                CO_UF                     Código da Unidade da Federação
2                SG_UF                      Sigla da Unidade da Federação
3                NO_UF                       Nome da Unidade da Federação
4         CO_MUNICIPIO                                Código do Município
5         NO_MUNICIPIO                                  Nome do Município
6            ID_ESCOLA                  Código da Escola no CENSO Escolar
7            NO_ESCOLA                    Nome da Escola no CENSO Escolar
8         TP_TIPO_REDE  Dependência Administrativa da Escola:\n1 - Fed...
9       TP_LOCALIZACAO      Localização da Escola:\n1 - Urbana\n2 - Rural
10          TP_CAPITAL  Área da Escola (relacionado ao Município):\n1 ...
11     QTD_ALUNOS_INSE  Quantidade de Alunos com INSE calculado utiliz...
12          MEDIA_INSE  Média do Indicador de Nível Socioeconômico dos...
13  INSE_CLASSIFICACAO  Classificação do Indicador de Nível Socioeconô...
14          PC_NIVEL_1  Percentual de alunos da Escola classificados n...
15          PC_NIVEL_2  Percentual de alunos da Escola classificados n...
16          PC_NIVEL_3  Percentual de alunos da Escola classificados n...
17          PC_NIVEL_4  Percentual de alunos da Escola classificados n...
18          PC_NIVEL_5  Percentual de alunos da Escola classificados n...
19          PC_NIVEL_6  Percentual de alunos da Escola classificados n...
20          PC_NIVEL_7  Percentual de alunos da Escola classificados n...
21          PC_NIVEL_8  Percentual de alunos da Escola classificados n...

In [ ]:
# Tipos de dados das variáveis do INSE 2023

for nivel, arquivo in arquivos_inse.items():

    xls = pd.ExcelFile(arquivo)
    aba_principal = xls.sheet_names[0]

    df_temp = pd.read_excel(
        arquivo,
        sheet_name=aba_principal
    )

    print("\n" + "=" * 70)
    print(f"{nivel.upper()} - TIPOS DE DADOS")
    print("=" * 70)

    print(df_temp.dtypes)

======================================================================
BRASIL - TIPOS DE DADOS
======================================================================
NU_ANO_SAEB          int64
TP_TIPO_REDE         int64
TP_LOCALIZACAO       int64
TP_CAPITAL           int64
QTD_ALUNOS_INSE      int64
MEDIA_INSE         float64
PC_NIVEL_1         float64
PC_NIVEL_2         float64
PC_NIVEL_3         float64
PC_NIVEL_4         float64
PC_NIVEL_5         float64
PC_NIVEL_6         float64
PC_NIVEL_7         float64
PC_NIVEL_8         float64
dtype: object

======================================================================
ESTADOS - TIPOS DE DADOS
======================================================================
NU_ANO_SAEB          int64
CO_UF                int64
SG_UF               object
NO_UF               object
TP_TIPO_REDE         int64
TP_LOCALIZACAO       int64
TP_CAPITAL           int64
QTD_ALUNOS_INSE      int64
MEDIA_INSE         float64
PC_NIVEL_1         float64
PC_NIVEL_2         float64
PC_NIVEL_3         float64
PC_NIVEL_4         float64
PC_NIVEL_5         float64
PC_NIVEL_6         float64
PC_NIVEL_7         float64
PC_NIVEL_8         float64
dtype: object

======================================================================
MUNICÍPIOS - TIPOS DE DADOS
======================================================================
NU_ANO_SAEB          int64
CO_UF                int64
SG_UF               object
NO_UF               object
CO_MUNICIPIO         int64
NO_MUNICIPIO        object
TP_TIPO_REDE         int64
TP_LOCALIZACAO       int64
TP_CAPITAL           int64
QTD_ALUNOS_INSE      int64
MEDIA_INSE         float64
PC_NIVEL_1         float64
PC_NIVEL_2         float64
PC_NIVEL_3         float64
PC_NIVEL_4         float64
PC_NIVEL_5         float64
PC_NIVEL_6         float64
PC_NIVEL_7         float64
PC_NIVEL_8         float64
dtype: object

======================================================================
ESCOLAS - TIPOS DE DADOS
======================================================================
NU_ANO_SAEB             int64
CO_UF                   int64
SG_UF                  object
NO_UF                  object
CO_MUNICIPIO            int64
NO_MUNICIPIO           object
ID_ESCOLA               int64
NO_ESCOLA              object
TP_TIPO_REDE            int64
TP_LOCALIZACAO          int64
TP_CAPITAL              int64
QTD_ALUNOS_INSE         int64
MEDIA_INSE            float64
INSE_CLASSIFICACAO     object
PC_NIVEL_1            float64
PC_NIVEL_2            float64
PC_NIVEL_3            float64
PC_NIVEL_4            float64
PC_NIVEL_5            float64
PC_NIVEL_6            float64
PC_NIVEL_7            float64
PC_NIVEL_8            float64
dtype: object

In [ ]:
# Verificação de valores nulos nas tabelas do INSE 2023

for nivel, arquivo in arquivos_inse.items():

    xls = pd.ExcelFile(arquivo)
    aba_principal = xls.sheet_names[0]

    df_temp = pd.read_excel(
        arquivo,
        sheet_name=aba_principal
    )

    nulos = df_temp.isna().sum()

    print("\n" + "=" * 70)
    print(f"{nivel.upper()} - VALORES NULOS")
    print("=" * 70)

    print(nulos[nulos > 0])

======================================================================
BRASIL - VALORES NULOS
======================================================================
Series([], dtype: int64)

======================================================================
ESTADOS - VALORES NULOS
======================================================================
Series([], dtype: int64)

======================================================================
MUNICÍPIOS - VALORES NULOS
======================================================================
MEDIA_INSE      890
PC_NIVEL_1       85
PC_NIVEL_2     4460
PC_NIVEL_3     1612
PC_NIVEL_4      520
PC_NIVEL_5      774
PC_NIVEL_6     2950
PC_NIVEL_7     7811
PC_NIVEL_8    42414
dtype: int64

======================================================================
ESCOLAS - VALORES NULOS
======================================================================
PC_NIVEL_1      265
PC_NIVEL_2     6720
PC_NIVEL_3     1922
PC_NIVEL_4     1339
PC_NIVEL_5     3483
PC_NIVEL_6     9030
PC_NIVEL_7    16497
PC_NIVEL_8    46332
dtype: int64

In [ ]:
# Inventário consolidado das bases do INSE 2023

resumo_inse = []

for nivel, arquivo in arquivos_inse.items():

    xls = pd.ExcelFile(arquivo)
    aba_principal = xls.sheet_names[0]

    df_temp = pd.read_excel(
        arquivo,
        sheet_name=aba_principal
    )

    resumo_inse.append({
        "Nível de agregação": nivel,
        "Tabela": aba_principal,
        "Linhas": df_temp.shape[0],
        "Colunas": df_temp.shape[1]
    })

inventario_inse = pd.DataFrame(resumo_inse)

display(inventario_inse)

  Nível de agregação         Tabela  Linhas  Colunas
0             Brasil   INSE_BR_2023      63       14
1            Estados   INSE_UF_2023    1552       17
2         Municípios  INSE_MUN_2023  125741       19
3            Escolas  INSE_ESC_2023   69756       22

## Inventário do INSE 2023

A análise estrutural do INSE 2023 identificou quatro tabelas principais, organizadas em diferentes níveis de agregação: Brasil, Unidades da Federação, municípios e escolas.

| Nível de agregação | Tabela | Registros | Variáveis |
|---|---|---:|---:|
| Brasil | INSE_BR_2023 | 63 | 14 |
| Estados | INSE_UF_2023 | 1.552 | 17 |
| Municípios | INSE_MUN_2023 | 125.741 | 19 |
| Escolas | INSE_ESC_2023 | 69.756 | 22 |

As tabelas apresentam uma estrutura hierárquica de identificação. Conforme aumenta o nível de detalhamento, são incorporadas informações geográficas e de identificação das unidades.

No nível municipal estão disponíveis os códigos e nomes dos municípios (`CO_MUNICIPIO` e `NO_MUNICIPIO`). No nível escolar, além da identificação municipal, estão disponíveis o código e o nome da escola (`ID_ESCOLA` e `NO_ESCOLA`).

As informações centrais do INSE são representadas pela quantidade de alunos considerados no cálculo (`QTD_ALUNOS_INSE`), pela média do indicador (`MEDIA_INSE`) e pela distribuição percentual dos alunos entre os níveis 1 a 8 (`PC_NIVEL_1` a `PC_NIVEL_8`).

Na tabela de escolas também está disponível a variável `INSE_CLASSIFICACAO`, relacionada à classificação do Indicador de Nível Socioeconômico.

A análise dos tipos de dados identificou variáveis numéricas inteiras para os campos de identificação e classificação e variáveis do tipo `float` para a média do INSE e os percentuais de distribuição por nível.

Quanto aos valores ausentes, não foram identificados valores nulos nas tabelas de Brasil e Estados. Na tabela de municípios foram identificados valores ausentes em `MEDIA_INSE` e nas variáveis `PC_NIVEL_1` a `PC_NIVEL_8`. Na tabela de escolas foram identificados valores ausentes nas variáveis `PC_NIVEL_1` a `PC_NIVEL_8`.

Os valores ausentes foram apenas identificados nesta etapa e não receberam tratamento, pois as regras de limpeza e transformação serão definidas posteriormente na camada Prata.

## Considerações sobre a utilização do INSE 2023

O INSE 2023 foi incorporado ao projeto como uma fonte externa complementar. Essa fonte não estava entre as bases originalmente relacionadas na documentação do trabalho.

A inclusão foi definida por sua aderência ao contexto educacional e ao recorte temporal de 2023.

A base apresenta informações em diferentes níveis de agregação, permitindo análises em nível nacional, estadual, municipal e escolar. A definição das tabelas e variáveis que serão efetivamente utilizadas nos cruzamentos será realizada posteriormente, a partir das perguntas analíticas e da modelagem do projeto.

Nesta etapa, o objetivo foi exclusivamente identificar, documentar e avaliar a estrutura da fonte. O tratamento dos dados, a seleção definitiva das variáveis e os relacionamentos entre as bases serão definidos nas etapas posteriores.